<?php
$translate = $this->plugin('translate');
$escape = $this->plugin('escapeHtml');
$labelInfo = $this->setting('property_label_information');
$not = array('Description');
$notalt = array('Collectie ID','Referenties object','Beeld','Beeld copyright','title','description');
?>
<?php $current_group = "Identificatie";?>
<?php foreach ($templateProperties as $term => $property): ?>
  <?php 
    if($property->isPrivate()):
      continue;
    endif;
    $propertyData = '';
    if(isset($values[$property->property()->term()])):
      $propertyData = $values[$property->property()->term()];
    else:
      continue;
    endif;
    
    $group = $propertyData['group'];
  ?>  
  <?php if($group):?>
    <?php if($group != $current_group):?>
    </div>
    <div id="<?php echo $group;?>" class="tab-pane animated">
    <?php $current_group = $group;?>
    <?php endif;?>
  <?php endif;?>  
  <?php if(!in_array($propertyData['property']->label(),$not) && !in_array($propertyData['alternate_label'],$notalt)):?>
    <div class="metadata-line"> 
      <div class="titles">        
          <label class="label">
          
          <?php if ($propertyData['alternate_label']): ?>
          <?php echo $escape($propertyData['alternate_label']); ?>
          <?php else: ?>
          <?php echo $escape($translate($propertyData['property']->label())); ?>
          <?php endif; ?>
          <?php if ('term' === $labelInfo): ?>
          <span class="field-term">(<?php echo $escape($propertyData['property']->term()); ?>)</span>
          <?php elseif ('vocab' === $labelInfo): ?>
          <span class="field-term">(<?php echo $escape($propertyData['property']->vocabulary()->label()); ?>)</span>
          <?php endif; ?>
          </label>        
      </div>
    
      <div class="values-col">
      <?php $i=0;?>
      <?php foreach ($propertyData['values'] as $value): ?>
          <?php
          $valueType = $value->type();
          $class = ['value'];
          if ('resource' == $valueType || strpos($valueType, 'resource') !== false) {
              $class[] = 'resource';
              $class[] = $escape($value->valueResource()->resourceName());
          } elseif ('uri' == $valueType) {
              $class[] = 'uri';
          }
          if (!$value->isPublic()) {
              $class[] = 'private';
          }
          ?>

            <div class="<?php echo $propertyData['property']->term(); ?> <?php echo implode(' ', $class); ?>" lang="<?php echo $escape($value->lang()); ?>">
                <?php if ($language = $value->lang()): ?>
                <!--<span class="language"><?php echo $language; ?></span>-->
                <?php endif; ?>

                <?php if($propertyData['alternate_label'] == 'Trefwoorden'):?>
                  <a target="_blank" href="https://slimerfgoed.be/s/zorgerfgoed/collecties?facet%5Bschema%3Agenre%5D%5B%5D=collectie&facet%5Bschema%3Akeywords%5D%5B%5D=<?php echo $value->asHtml(); ?>"><?php echo $value->asHtml(); ?></a>
                
                <?php elseif($propertyData['alternate_label'] == 'Bouwjaar'):?>
                  <?php echo rtrim($value->asHtml(),"-"); ?>
                <?php else:?>
                  <?php echo $value->asHtml(); ?>
                <?php endif;?>
            </div>
            <?php $i++;?>
      <?php endforeach; ?>
    </div>  
  </div>
  <?php endif;?>
<?php endforeach; ?>
