<?php
use Zend\Form\Element\Textarea;
use Zend\Form\Element;

$api = $this->api()->search('items',['resource_template_id' => 33]);
$authors = $api->getContent();

$apiSet = $this->api()->search('item_sets', ['site_id' => 18]);
$itemsets = $apiSet->getContent();

echo $this->blockAttachmentsForm($block);
?>
<h4>Title</h4>
<div class="field">
  <div class="inputs">
      <input type="text" class="" value="<?php echo (!isset($block) ? '' : $block->dataValue('title')); ?>" name="o:block[__blockIndex__][o:data][title]">
  </div>
</div>
<h4>Secondary Title</h4>
<div class="field">
  <div class="inputs">
      <input type="text" class="" value="<?php echo (!isset($block) ? '' : $block->dataValue('sec_title')); ?>" name="o:block[__blockIndex__][o:data][sec_title]">
  </div>
</div>
<h4>Text</h4>
<?php
  $textarea = new Textarea("o:block[__blockIndex__][o:data][text]");
  $textarea->setAttribute('class', 'block-html full wysiwyg');
  if ($block) {
      $textarea->setAttribute('value', $block->dataValue('text'));
  }
?>
<?php echo $this->formRow($textarea);?>

<h4>Use custom sorting?</h4>
<div class="field">
  <label class="checkbox" style="padding-left:1em;">
    <input value="checked" type="checkbox" name="o:block[__blockIndex__][o:data][customsort]" <?php if($block):if($block->dataValue('customsort')):?>checked<?php endif;endif?>>
    If checked items will be displayed according to the attachments
  </label>
</div>

<h4>Item set</h4>
<div class="field">
  <div class="inputs" style="padding-right:1em;">
    <select name="o:block[__blockIndex__][o:data][itemset]">
      <option value="">None</option>
    <?php foreach ($itemsets as $itemset):?>
      <option value="<?php echo $itemset->id(); ?>" <?php if($block):if($block->dataValue('itemset') == $itemset->id()):?>selected<?php endif;endif?>><?php echo $itemset->title();?></option>
    <?php endforeach;?>
    </select>
  </div>
</div>

<h4>Show collection on map?</h4>
<div class="field">
  <label class="checkbox" style="padding-left:1em;">
    <input value="checked" type="checkbox" name="o:block[__blockIndex__][o:data][map]" <?php if($block):if($block->dataValue('map')):?>checked<?php endif;endif?>>
    If checked a button will appear that leads to a map displaying the items in the collection.
  </label>
</div>

<h4>Author(s)</h4>
<?php $i=0;?>
<div class="field">
  <div class="checkboxes">
    <?php foreach($authors as $author):?>
      <label class="checkbox" style="padding-right:1em;">
        <input value="<?php echo $author->id(); ?>" type="checkbox" name="o:block[__blockIndex__][o:data][author<?php echo $i;?>]" <?php if($block):if($block->dataValue('author'.$i)):?>checked<?php endif;endif?>>
          <?php echo $author->value('schema:givenName') . " " . $author->value('schema:familyName'); ?>
      </label>
      <?php $i++;?>
    <?php endforeach;?>
  </div>
  <input hidden value="<?php echo $i;?>" name="o:block[__blockIndex__][o:data][numberofauthors]">
</div>