<?php
/**
 * @var \Laminas\View\Renderer\PhpRenderer $this
 * @var \Contribute\Form\ContributeForm $form
 * @var \Omeka\Api\Representation\AbstractResourceEntityRepresentation $resource
 * @var \Contribute\Api\Representation\ContributionRepresentation[] $contributions
 * @var \Contribute\Api\Representation\TokenRepresentation[] $unusedTokens
 * @var string $siteSlug
 */

$plugins = $this->getHelperPluginManager();
$api = $plugins->get('api');
$setting = $plugins->get('setting');
$escape = $plugins->get('escapeHtml');
$translate = $plugins->get('translate');
$hyperlink = $plugins->get('hyperlink');
$escapeAttr = $plugins->get('escapeHtmlAttr');
?>

<div class="contributions">
    <?php $totalTokens = $api->search('contribution_tokens', ['resource_id' => $resource->id(), 'limit' => 0])->getTotalResults(); ?>
    <?php if (empty($totalTokens)): ?>
        <?php if (in_array($setting('contribute_mode'), ['user_token', 'token'])): ?>
    <div class="no-resources no-tokens">
        <p><?= $translate('There are no tokens for this resource or contribution mode doesn’t use token.') ?></p>
    </div>
        <?php endif; ?>
    <?php else: ?>
    <?php $totalExpiredTokens = $api
        ->search(
            'contribution_tokens',
            ['resource_id' => $resource->id(), 'datetime' => [['field' => 'expire', 'type' => 'lt', 'value' => date('Y-m-d H:i:s')]]]
        )
        ->getTotalResults(); ?>
    <div class="contribution-token">
        <p><?= sprintf($translate('There are %d tokens for this resource (%d expired).'), $totalTokens, $totalExpiredTokens) ?></p>
        <?php if (($totalTokens - $totalExpiredTokens) && $this->userIsAllowed('Contribute\Controller\Admin\Contribution', 'expire-tokens')): ?>
        <?= $hyperlink($translate('Expire all tokens'), $this->url('admin/contribution/id', ['action' => 'expire-tokens', 'id' => $resource->id()]), ['class' => 'button']) ?>
        <?php endif; ?>
    </div>
    <?php endif; ?>

<?php if (empty($contributions)): ?>
    <div class="no-resources no-contributions">
        <p><?= $translate('There are no contributions for this resource.') ?></p>
    </div>
<?php else: ?>
<?php
$mapResourceAdapters = [
    'item' => \Omeka\Api\Adapter\ItemAdapter::class,
    'media' => \Omeka\Api\Adapter\ItemSetAdapter::class,
    'item-set' => \Omeka\Api\Adapter\MediaAdapter::class,
];
$resourceName = $resource->getControllerName();
$adapterName = $mapResourceAdapters[$resourceName];
$batchEditRight = $this->userIsAllowed($adapterName, 'batch-update');
$editRight = $resource->userIsAllowed('update');
?>
<?php foreach ($contributions as $contribution): ?>
<?php $token = $contribution->token(); ?>
<div class="contribution">
<table class="tablesaw <?php if ($batchEditRight) echo 'batch-edit'; ?>" data-tablesaw-mode="stack">
    <thead>
        <tr>
            <th>
                <?= $translate('Contribution') ?>
                <?php /*
                <span class="contribution-id">#<?= $contribution->id() ?></span>
                */ ?>
                <?php if ($email = $contribution->email()): ?>
                <span class="contribution-email"><?= $hyperlink($email, 'mailto:' . $email) ?></span>
                <?php endif; ?>

                <span class="contribution-date"><?= $this->i18n()->dateFormat($contribution->created(), 'medium', 'medium') ?></span>

                <?php if ($contribution->created() != $contribution->modified()): // Don't use !==. ?>
                <span class="contribution-date-modified"><?= $translate('(modified)') ?></span>
                <?php endif; ?>

                <?php if ($token): ?>
                <span> / </span>
                <span class="contribution-token"><?= $hyperlink($token->token(), $token->siteUrl($siteSlug, true)) ?></span>
                <?php endif; ?>

                <?php if ($contribution->isPatch()): // Only patchs should be validated individually. ?>

                <?php if ($editRight): ?>
                <?php // TODO Check if all values are the same to change the default icon to "validated". ?>
                <span class="single actions"><a href="#"
                    class="validate o-icon-validate"
                    data-validate-url="<?= $escape($contribution->adminUrl('validate')) ?>"
                    data-status="validate"
                    aria-label="<?= $escape($translate('Validate all values')) ?>"
                    title="<?= $escape($translate('Validate all values')) ?>"></a></span>
                <span class="single actions"><a href="#"
                    class="status-toggle o-icon-<?= $contribution->isReviewed() ? 'reviewed' : 'unreviewed' ?>"
                    data-status-toggle-url="<?= $escape($contribution->adminUrl('toggle-status')) ?>"
                    data-status="<?= $contribution->isReviewed() ? 'reviewed' : 'unreviewed' ?>"
                    aria-label="<?= $escape($translate('Toggle status reviewed/unreviewed')) ?>"
                    title="<?= $escape($translate('Toggle status reviewed/unreviewed')) ?>"></a></span>
                <?php endif; ?>

                <?php if ($token && $token->isExpired()): ?>
                <span class="single no-action o-icon-expired-token" aria-label="<?= $escape($translate('Expired token')) ?>"></span>
                <?php elseif ($token): ?>
                <span class="single single-action"><a href="#"
                    class="expire-token o-icon-expire-token"
                    data-expire-token-url="<?= $escape($contribution->adminUrl('expire-token')) ?>"
                    aria-label="<?= $escape($translate('Expire token')) ?>"
                    title="<?= $escape($translate('Expire token')) ?>"></a></span>
                <?php endif; ?>

                <?php else: ?>

                <span class="single actions"><a href="#"
                    class="status-toggle o-icon-<?= $contribution->isReviewed() ? 'reviewed' : 'unreviewed' ?>"
                    data-status-toggle-url="<?= $escape($contribution->adminUrl('toggle-status')) ?>"
                    data-status="<?= $contribution->isReviewed() ? 'reviewed' : 'unreviewed' ?>"
                    aria-label="<?= $escape($translate('Toggle status reviewed/unreviewed')) ?>"
                    title="<?= $escape($translate('Toggle status reviewed/unreviewed')) ?>"></a></span>

                <?php endif; ?>
            </th>
        </tr>
    </thead>
    <tbody>
        <tr class="contribution-value">
            <td>
                <?php
                $proposal = $contribution->proposalNormalizeForValidation();
                $vars = $this->vars();
                $varsBase = $vars->getArrayCopy();
                $varsBase['api'] = $api;
                $varsBase['escape'] = $escape;
                $varsBase['translate'] = $translate;
                $varsBase['hyperlink'] = $hyperlink;
                $varsBase['escapeAttr'] = $escapeAttr;
                $varsBase['contribution'] = $contribution;
                $varsBase['editRight'] = $editRight;
                $varsBase['labelInfo'] = $setting('property_label_information');
                $varsBase['values'] = $resource->values();
                $varsBase['isSubProposal'] = false;
                $varsBase['proposal'] = $proposal;
                echo $this->partial('common/admin/contribute-list-part', $varsBase);
                if (isset($proposal['media']) && count($proposal['media'])):
                    // No upper div to simplify admin theme.
                    ?>
                    <div class="contribution-medias">
                        <h4 class="contribution-medias-label"><?= $translate('Medias') ?></h4>
                        <?php
                        // TODO Currently, only new media are managed as sub-resource: contribution for new resource, not contribution for existing item with media at the same time.
                        $varsBase['values'] = [];
                        $varsBase['isSubProposal'] = true;
                        $varsForLoop = [];
                        foreach ($proposal['media'] ?? [] as $subProposal) {
                            $varsBase['proposal'] = $subProposal;
                            $varsForLoop[] = $varsBase;
                        }
                        echo $this->partialLoop('common/admin/contribute-list-part', $varsForLoop);
                        ?>
                        
                    </div>
                <?php endif; ?>

               
                <?php if (isset($proposal["mapping"]['markers']) && count($proposal["mapping"])):
                    // No upper div to simplify admin theme.
                    ?>
                    <div class="contribution-medias">
                        <div class="property">
                            <h4>Mapping</h4>
                            <?php                                
                                // Add mapping data.
                                $map_set = false;
                                $mapping = $this->api()->search('mappings', ['item_id' => $this->resource->id()])->getContent();
                                
                                $features = $this->api()->search('mapping_markers', ['item_id' => $resource->id()])->getContent();
                                // echo json_encode($features[0]->getJsonLd());
                                if(isset($proposal['mapping']['markers'][0])){
                                if(is_array($proposal['mapping']['markers'][0]['proposed']['@value'])){
                                    if($features){                                    
                                        if(
                                            $proposal['mapping']['markers'][0]['proposed']['@value'][array_key_first($proposal['mapping']['markers'][0]['proposed']['@value'])]["o-module-mapping:lat"] == $features[0]->lat() &&
                                            $proposal['mapping']['markers'][0]['proposed']['@value'][array_key_first($proposal['mapping']['markers'][0]['proposed']['@value'])]["o-module-mapping:lng"] == $features[0]->lng()
                                        ){                                       
                                            $map_set = true;
                                        }      
                                    }
                                }  
                                }                             
                            ?>
                            <div class="values">
                                <div>
                                    <div>
                                        <span class="mapping">
                                       <?php
                                        if (isset($proposal['mapping']['bounds'][0]['proposed']['@value'])):
                                            echo "<h6>Bounds map</h6>";
                                            if($mapping && $features){
                                                echo '<span data-name="mapping" class="original-value">'.$mapping[0]->bounds().'</span><br>';
                                            }
                                            echo $proposal['mapping']['bounds'][0]['proposed']['@value']["o-module-mapping:bounds"];
                                            endif;
                                        if (isset($proposal['mapping']['markers'][0]['proposed']['@value'])):
                                            echo "<h6>Marker Latitude / longitude</h6>";
                                            if($mapping && $features){
                                                echo '<span data-name="mapping" class="original-value">'.$features[0]->lat().' / '.$features[0]->lng().'</span><br>';
                                            }
                                            foreach($proposal['mapping']['markers'][0]['proposed']['@value'] as $marker):
                                                echo $marker["o-module-mapping:lat"];
                                                echo " / ".$marker["o-module-mapping:lng"];                                        
                                            endforeach;    
                                        endif;    
                                        ?>                                        
                                        </span>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <?php if ($contribution->isPatch()): // Only patchs should be validated individually. ?>
                            
                            <span class="single actions">           
                                <?php if(!$map_set):?>                                             
                                        <a href="#"
                                            class="validate-value o-icon-validate-value"
                                            data-validate-value-url="<?= $escapeAttr($contribution->adminUrl('validate-value')) ?>?term=mapping&key=0"
                                            data-status="validate-value"
                                            aria-label="<?= $txt = $escapeAttr(sprintf($translate('Validate this value (%s)'), $translate($process))) ?>"
                                            title="<?= $txt ?>"></a>                                
                                <?php else:?>
                                    <span class="no-action o-icon-validated-value" aria-label="<?= $escapeAttr($translate('Validated')) ?>"></span>
                                <?php endif; ?>
                            </span>
                        <?php endif; ?>
                        <?php
                        
                        //echo $this->partialLoop('common/admin/contribute-list-part', $proposal["mapping"]);
                        ?>
                    </div>
                <?php endif; ?>
            </td>
        </tr>
        <?php endforeach; ?>
    </tbody>
</table>
</div>

<?php endif; ?>

<?php if ($unusedTokens): ?>
<h4><?= $translate('Unused tokens') ?></h4>
<?= $this->partial('common/admin/contribute-token-list', [
    'resource' => $resource,
    'tokens' => $unusedTokens,
    'siteSlug' => $siteSlug,
]) ?>
<?php endif; ?>

</div>
