<?php
use Zend\Form\Element\Textarea;
use Zend\Form\Element;

$api = $this->api()->search('items',['resource_template_id' => 33]);
$authors = $api->getContent();

echo $this->blockAttachmentsForm($block);
?>
<h4>Title</h4>
<div class="field">
  <div class="inputs">
      <input type="text" class="" value="<?php echo (!isset($block) ? '' : $block->dataValue('title')); ?>" name="o:block[__blockIndex__][o:data][title]">
  </div>
</div>
<h4>Secondary Title</h4>
<div class="field">
  <div class="inputs">
      <input type="text" class="" value="<?php echo (!isset($block) ? '' : $block->dataValue('sec_title')); ?>" name="o:block[__blockIndex__][o:data][sec_title]">
  </div>
</div>
<h4>Text</h4>
<?php
  $textarea = new Textarea("o:block[__blockIndex__][o:data][text]");
  $textarea->setAttribute('class', 'block-html full wysiwyg');
  if ($block) {
      $textarea->setAttribute('value', $block->dataValue('text'));
  }
?>
<?php echo $this->formRow($textarea);?>

<h4>Author</h4>
<?php $i=0;?>
<div class="field">
  <div class="checkboxes">
    <?php foreach($authors as $author):?>
      <label class="checkbox" style="padding-right:1em;">
        <input value="<?php echo $author->id(); ?>" type="checkbox" name="o:block[__blockIndex__][o:data][author<?php echo $i;?>]" <?php if($block): if($block->dataValue('author'.$i)):?>checked<?php endif;endif;?>>
          <?php echo $author->value('schema:givenName') . " " . $author->value('schema:familyName'); ?>
      </label>
      <?php $i++;?>
    <?php endforeach;?>
  </div>
  <input hidden value="<?php echo $i;?>" name="o:block[__blockIndex__][o:data][numberofauthors]">
  <!-- <div class="inputs">
     <select name="o:block[__blockIndex__][o:data][author]">
      <?php foreach ($authors as $author):?>
        <option value="<?php echo $author->id(); ?>"><?php echo $author->value('schema:givenName') . " " . $author->value('schema:familyName');?></option>
      <?php endforeach;?>
     </select>
  </div> -->
</div>

<!-- <input type="select" value="<?php echo (!isset($block) ? '' : $block->dataValue('author')) ?>" name="o:block[__blockIndex__][o:data][author]"> -->
