<?php
use Zend\Form\Element\Textarea;
use Zend\Form\Element;

$api = $this->api()->search('items',['resource_template_id' => 33]);
$authors = $api->getContent();

echo $this->blockAttachmentsForm($block);
?>
<h4>Title</h4>
<div class="field">
  <div class="inputs">
      <input type="text" class="" value="<?php echo (!isset($block) ? '' : $block->dataValue('title')); ?>" name="o:block[__blockIndex__][o:data][title]">
  </div>
</div>
<h4>Secondary Title</h4>
<div class="field">
  <div class="inputs">
      <input type="text" class="" value="<?php echo (!isset($block) ? '' : $block->dataValue('sec_title')); ?>" name="o:block[__blockIndex__][o:data][sec_title]">
  </div>
</div>
<h4>Text</h4>
<?php
  $textarea = new Textarea("o:block[__blockIndex__][o:data][text]");
  $textarea->setAttribute('class', 'block-html full wysiwyg');
  if ($block) {
      $textarea->setAttribute('value', $block->dataValue('text'));
  }
?>
<?php echo $this->formRow($textarea);?>
<h4>Author</h4>
<div class="field">
  <div class="inputs">
     <select name="o:block[__blockIndex__][o:data][author]">
      <?php foreach ($authors as $author):?>
        <option value="<?php echo $author->id(); ?>"><?php echo $author->value('schema:givenName') . " " . $author->value('schema:familyName');?></option>
      <?php endforeach;?>
     </select>
  </div>
</div>

<!-- <input type="select" value="<?php echo (!isset($block) ? '' : $block->dataValue('author')) ?>" name="o:block[__blockIndex__][o:data][author]"> -->


