<?php
$translate = $this->plugin('translate');
$escape = $this->plugin('escapeHtml');
$this->htmlElement('body')->appendAttribute('class', 'item resource show');
$embedMedia = $this->siteSetting('item_media_embed', false);
$itemMedia = $item->media();
$download = array();

$template = $item->resourceTemplate();
$itemMedia = $resource->media();
?>
<section class="section breadcrumb-section">
  <div class="container">
    <nav class="breadcrumb" aria-label="breadcrumbs">
      <ul>
        <li><a href="<?php echo $site->url();?>/page/home">Home</a></li>
        <?php if($template && $template->id() == 33): ?>
          <li><?php echo $item->value('schema:givenName') . ' ' . $item->value('schema:familyName'); ?></li>
        <?php else:?>
        <li><?php echo $item->displayTitle(); ?></li>
        <?php endif;?>
      </ul>
    </nav>
  </div>
</section>

<?php if($template && $template->id() == 33):;?>
<section class="section">
  <div class="container">
    <div class="columns">
      <div class="column is-4">
        <div class="media-embeds" style="text-align:center;">
        <?php foreach ($itemMedia as $media):
            echo $media->render();
        endforeach;?>
        </div>
      </div>
      <div class="column is-5">
        <ul>
          <li><b><?php echo $item->value('schema:givenName') . ' ' . $item->value('schema:familyName'); ?></b></li>
          <li><?php echo $item->value('schema:hasOccupation'); ?></li>
          <li><?php echo $item->value('schema:worksFor'); ?></li>
          <?php if($item->value('schema:email')):?>
          <li><a href="mailto:<?php echo $item->value('schema:email')->uri(); ?>"><?php echo $item->value('schema:email'); ?></a></li>
          <?php endif;?>
        </ul>
      </div>
    </div>
  </div>
</section>

<?php else:?>
<section class="section">
  <div class="container">
    <div class="columns">
        <?php if (!$embedMedia && $itemMedia): ?>
          <div class="slide-container">
             <div class="slider-for">
               <?php $count = 0;?>
               <?php foreach($itemMedia as $media):?>                 
                   <?php $count++;?>
                   <?php if($media->mediaType() != 'application/pdf'):?> 
                   <div class="has-text-centered">
                     <?php $url = str_replace('http:', '', $media->thumbnailUrl('large'));?>                     
                     <?php echo $media->render();?> 
                   </div>
                   <?php endif;?>
                 <?php if($media->mediaType() == 'application/pdf'):?>
                   <?php if($media->value('dcterms:title')):?>
                     <?php $download[$media->filename()]['url'] = $media->originalUrl();?>
                     <?php $download[$media->filename()]['label'] = $media->value('dcterms:title');?>
                   <?php else:?>                    
                     <?php $download[$media->filename()]['url'] = $media->originalUrl();?>
                     <?php $download[$media->filename()]['label'] = 'Download';?>
                   <?php endif;?>
                 <?php endif;?>
               <?php endforeach;?>
             </div>
             <?php if($count > 1):?>
               <div class="slider-nav" role="toolbar">
                 <?php foreach($itemMedia as $media):?>
                   <?php if($media->mediaType() != 'application/pdf'):?>
                     <?php $url = str_replace('http:', '', $media->thumbnailUrl('square'));?>
                     <img src="<?php echo $url;?>">
                  <?php endif;?>
                 <?php endforeach;?>
               </div>
             <?php endif;?>
         </div>
        <?php endif; ?>

        <div class="column"> 
          <div class="content show-metadata">
            <?php $this->trigger('view.show.before'); ?>
            <?php if ($embedMedia && $itemMedia): 
              $itemMedia = $resource->media();
            $sortedMedia = $this->SortMedia($itemMedia);
            $lightMedia = (isset($sortedMedia['lightMedia'])) ? $sortedMedia['lightMedia'] : null;
            $otherMedia = (isset($sortedMedia['otherMedia'])) ? $sortedMedia['otherMedia'] : null;
            ?>
            <?php if (isset($lightMedia)): ?>
                <?php echo $this->LightGalleryOutput($lightMedia); ?>
            <?php endif; ?>
                <?php foreach ($itemMedia as $media):
                    echo $media->render();
                endforeach;
                ?>
                </div>
            <?php endif; ?>
            <?php if($download):?>
              <div class="">
                <h3 class="is-title is-3">Download</h3>
                <?php foreach($download as $link):?>
                  <a href="<?php echo $link['url'];?>" class="button is-text">
                    <span class="icon"><i class="fa fa-file-pdf-o"></i></span>
                    <span><?php //echo $name;?><?php echo $link['label'];?></span>
                  </a><br />
                <?php endforeach;?>
              </div>
              <hr />
            <?php endif;?>

            <?php echo $item->displayValues(); ?>
            <?php $itemSets = $item->itemSets(); ?>
            <?php if($item->value('dcterms:source')):?>
              <?php $infos = $item->value('dcterms:source',["all" => true]);?>
              <hr />

            <?php endif;?>

          </div>
  </div>
  </div>
  </div>
  </section>

<?php endif;?>
