<?php
$translate = $this->plugin('translate');
$escape = $this->plugin('escapeHtml');
$labelInfo = $this->setting('property_label_information');
$not = array('Title','Description','Is Version Of','Is Part Of','Language','Provenance');
$notalt = array('Collectie ID','Referenties object','Beeld','Beeld copyright','title','description','In de kijker');
?>

<?php foreach ($templateProperties as $term => $property): ?>
  <?php 
    if($property->isPrivate()):
      continue;
    endif;
    $propertyData = '';
    if(isset($values[$property->property()->term()])):
      $propertyData = $values[$property->property()->term()];
    else:
      continue;
    endif;
    $comment = '';
    $comment = $property->alternateComment();
  ?>  
  <?php if(!in_array($propertyData['property']->label(),$not) && !in_array($propertyData['alternate_label'],$notalt)):?>
  <div class="columns ">
    <?php if($comment != 'no label'):?>
      <div class="column is-3" style="padding-top:0.3rem;padding-bottom:0.3rem;">        
          <h4 class="title is-6" style="font-size:0.9rem;">
          <?php if ($propertyData['alternate_label']): ?>
          <?php echo $escape($propertyData['alternate_label']); ?>
          <?php else: ?>
          <?php echo $escape($translate($propertyData['property']->label())); ?>
          <?php endif; ?>
          <?php if ('term' === $labelInfo): ?>
          <span class="field-term">(<?php echo $escape($propertyData['property']->term()); ?>)</span>
          <?php elseif ('vocab' === $labelInfo): ?>
          <span class="field-term">(<?php echo $escape($propertyData['property']->vocabulary()->label()); ?>)</span>
          <?php endif; ?>
          </h4>        
      </div>
    <?php endif;?>
    <div class="column is-7" style="padding-top:0.3rem;padding-bottom:0.3rem;">
      <div class="values" style="font-size:0.9rem;">
      <?php $i=0;?>
      <?php foreach ($propertyData['values'] as $value): ?>
          <?php
          $valueType = $value->type();
          $class = ['value'];
          if ('resource' == $valueType || strpos($valueType, 'resource') !== false) {
              $class[] = 'resource';
              $class[] = $escape($value->valueResource()->resourceName());
          } elseif ('uri' == $valueType) {
              $class[] = 'uri';
          }
          if (!$value->isPublic()) {
              $class[] = 'private';
          }
          ?>

            <div class="<?php echo $propertyData['property']->term(); ?> <?php echo implode(' ', $class); ?>" lang="<?php echo $escape($value->lang()); ?>">
                <?php if ($language = $value->lang()): ?>
                <!--<span class="language"><?php echo $language; ?></span>-->
                <?php endif; ?>

                <?php if($propertyData['alternate_label'] == 'Trefwoorden'):?>
                  <a target="_blank" href="https://slimerfgoed.be/s/zorgerfgoed/collecties?facet%5Bschema%3Agenre%5D%5B%5D=collectie&facet%5Bschema%3Akeywords%5D%5B%5D=<?php echo $value->asHtml(); ?>"><?php echo $value->asHtml(); ?></a>
                                
                <?php elseif (strpos($value->asHtml(), 'http') !== false && strpos($value->asHtml(), 'uri-value-link') === false):?>
                  <a target="_blank" href="<?php echo $value->asHtml(); ?>"><?php echo $value->asHtml(); ?></a>
                <?php else:?>
                  <?php echo $value->asHtml(); ?>
                <?php endif;?>
            </div>
            <?php $i++;?>
      <?php endforeach; ?>
      </div>
    </div>
  </div>
  <?php endif;?>
<?php endforeach; ?>
