<?php
/**
 * @var \Laminas\View\Renderer\PhpRenderer $this
 * @var \Omeka\Api\Representation\SiteRepresentation $site
 * @var \Contribute\Api\Representation\ContributionRepresentation|null $contribution
 * @var \Omeka\Api\Representation\AbstractResourceEntityRepresentation|null $resource
 * @var string $space "default" or "guest"
 */

$plugins = $this->getHelperPluginManager();
$partial = $plugins->get('partial');
$escape = $plugins->get('escapeHtml');
$translate = $plugins->get('translate');
$escapeAttr = $plugins->get('escapeHtmlAttr');

// Medias are displayed through displayValues() for now.
// $medias = $contribution->valuesMedias();
// $embedMedia = $siteSetting('item_media_embed', false);

$siteSlug = $this->params()->fromRoute('site-slug');

$this->vars()->offsetSet('skipContributeCss', false);
$partial('contribute/site/contribution/asset-include');

$this->htmlElement('body')->appendAttribute('class', 'contribution resource show');
?>

<div class="contribute-resource conbribute-show container <?= $space && $space !== 'default' ? $space : '' ?>">

    <h1 class="title is-2 is-family-secondary"><?php echo $contribution->displayTitle(); ?></h1>
    <div class="subtitle is-4 is-family-secondary">Aanvulling</div>

    <ul class="contribution-status" style="margin-bottom:2rem;">
        <li class="contribution-resource"><?= $resource ? $resource->linkPretty() : "De kapel heeft nog geen vaste link" ?></li>
        <li class="submitted"><?= $escape($contribution->isSubmitted() ? "De kapel is al ingediend" : "De kapel is nog niet ingediend") ?></li>
        <li class="reviewed"><?= $escape($contribution->isReviewed() ? "De kapel werd nagekeken" : "De kapel werd nog niet nagekeken") ?></li>
    </ul>

    <div class="messages">
        <?= $this->messages() ?>
    </div>

    <?php $this->trigger('view.show.before'); ?>


    <?php if (!$contribution->isSubmitted()): ?>
    <div class="actions" style="margin:2rem 0 0 0"  data-message-remove-contribution="<?= $escapeAttr($translate('Are you sure to remove this contribution?')) ?>">
        <?php if ($contribution->userIsAllowed('update')): ?>
        <a class="o-icon-edit button edit-button edit-contribution" href="<?= $escapeAttr($contribution->siteUrl($siteSlug, false, 'edit', $space === 'guest')) ?>"><?= $escape($translate('Edit')) ?></a>
        <?php endif; ?>
        <a class="button submit-button submit-contribution" href="<?= $escapeAttr($contribution->siteUrl($siteSlug, false, 'submit', $space === 'guest')) ?>"><?= $escape($translate('Indienen')) ?></a>
        <?php if ($contribution->userIsAllowed('delete')): ?>
        <a class="o-icon-delete button delete-button remove-contribution" data-contribution-id="<?= $contribution->id() ?>" data-contribution-url="<?= $escapeAttr($contribution->siteUrl($siteSlug, false, 'delete', $space === 'guest')) ?>" href="#"><?= $escape($translate('Delete')) ?></a>
        <?php endif; ?>
    </div>
    <?php endif; ?>

    <?php $this->trigger('view.show.after'); ?>

</div>
