<!-- overview blocks -->
<style>
.zigzag {
  display: inline-block;
  position: relative;
}

.zigzag:after {
  content: '';
  height: 18px;
  width: 100%;
  position: absolute;
  background: url("https://cldup.com/MiGVGBh-0U.png");
  background-size: 30px;
  top: 35px;
  bottom: 0px;
  left: 0;
}
.card-content {
  background-color: rgba(0,0,0,0.36);
  padding: 1.5rem;
  bottom: 0;
  position:absolute;
  width: 100%;
  height: 40%;
  transition: transform 250ms;
  transition-property: height;
}
</style>

<?php if($attachments):?>
  <section class="section items-section">
    <div class="container">
      <?php if($block->dataValue('title')):?>
        <div class="arrow-left"></div>
        <h2 class="title is-family-secondary"><?php echo $block->dataValue('title');?></h2>
      <?php endif;?>  
      <div class="columns">
          <?php  for($i = 1; $i <= sizeof($attachments); $i++){ ?>
            <?php
                $media = $attachments[$i-1]->media();
                $item = $media->item();
                $url = '';
                if($media):
                  if($media->mediaType() == 'text/html'):
                    $url = $media->originalUrl();
                    $url = str_replace('http:', '', $url);
                  else:
                    $url = $media->thumbnailUrl('large');
                    $url = str_replace('http:', '', $url);
                  endif;
                endif;
            ?>
            <div class="column is-4">
              <!-- <a href="<?php echo $item->url();?>">
                <div class="items-block" style="background:url(<?php echo  $url;?>) no-repeat center 20%;background-color:#7fb5b2;background-size: cover;min-height:250px;">
                  <div class="overlay"></div>
                </div>
                <div class="items-content">
                    <h3 class="title is-3 is-family-secondary">
                        <span><?php echo $item->displayTitle();?></span>
                    </h3>
                    <p>
                      <?php echo $item->displayDescription();?>
                    </p>
                    <div class="button"><a href="<?php echo $item->url();?>">Lees </a></div>
                    
                </div>
              </a>      -->
              <a href="<?php echo $item->url();?>">
          <div class="card equal-height card-hover-<?php echo $i;?>" onpointerenter="showCardContent(<?php echo $i;?>)";>              
            <div class="bg-block" style="background:url(<?php echo  $url;?>) no-repeat center 20%;background-color:#aaa;background-size: cover; min-height:250px;">
            <div class="overlay"></div>

            <div class="card-content" id="card-<?php echo $i;?>">
              <div class="content">
              <div class="card-top">
              <h3 class="title is-5 is-family-secondary has-text-white" id="title-<?php echo $i;?>">
                  <?php echo $item->displayTitle();?>
              </h3>
            </div>
            <div class="is-hidden has-text-white" id="body-<?php echo $i;?>">
                <?php if ($item->displayDescription()): ?>
                    <?php echo $item->displayDescription(); ?>
                <?php endif; ?>
                </div> 
              </div>
            </div>
            </div>
          </div>
        </a>         
            </div>              
          <?php } ?>
        </div>
        <?php if($block->dataValue('link')):?>
          <div class="has-text-right">
            <a class="button is-outlined is-white" href="<?php echo $block->dataValue('link');?>">
              <span>Lees meer</span>
              <span class="icon is-small">
                <i class="fas fa-angle-right"></i>
              </span>
            </a>
          </div>  
        <?php endif;?>  
    </div>
</section>
<?php endif;?>
<script>
function showCardContent(x){
  let id = '#card-' + x;
  let hover = '.card-hover-' + x;
  let idtitle = '#title-' + x;
  let idbody = '#body-' + x;
  $(hover).hover(function(){
    $( id ).css("height","100%");
    $( idtitle ).addClass("is-hidden");
    $( idbody ).removeClass( "is-hidden" );
  }, function() {
    $( idtitle ).removeClass( "is-hidden" );
    $( id ).css("height","40%");
    $( idbody ).addClass( "is-hidden" );
  })
}
</script>