
<div class="columns is-justify-content-center">
    <div class="column is-6-tablet is-5-desktop is-4-widescreen is-3-fullh">
      <form method="POST" action="https://herotofu.com/start" class="box p-5">
        <label class="is-block mb-4">
          <span class="is-block mb-2">Your name</span>
          <input
            name="name"
            type="text"
            class="input"
            placeholder="Joe Bloggs"
          />
        </label>

        <label class="is-block mb-4">
          <span class="is-block mb-2">Email address</span>
          <input
            required
            name="email"
            type="email"
            class="input"
            placeholder="joe.bloggs@example.com"
          />
        </label>

        <label class="is-block mb-4">
          <span class="is-block mb-2">Message</span>
          <textarea
            name="message"
            class="textarea"
            rows="3"
            placeholder="Tell us what you're thinking about..."
          ></textarea>
        </label>

        <div class="mb-4">
          <button type="submit" class="button is-link px-4">Contact Us</button>
        </div>
      </form>
    </div>
  </div>
</div>