<style>
  .content {
     font-size:1em; /* of 16px */
  }
  .content a:hover {
    border-bottom:2px solid #e29ca7;
  }
</style>

<section class="section intro-section" style="margin-bottom: 0;">
  <div class="container">

      <div class="columns">
          <?php if(sizeof($attachments)>0):?>
          <div class="column is-6">
          <?php else:?>
            <!-- <div class="column is-2"></div> -->
          <div class="column is-11">  
          <?php endif;?>
            <div class="content">
              <?php if($block->dataValue('title')):?>
            <div class="arrow-left"></div><h1 class="title is-3 is-family-secondary"><?php echo $block->dataValue('title');?></h1>
            <?php endif;?>
              <?php echo $block->dataValue('text');?>
            </div>
          </div>
          <?php if(sizeof($attachments)>0):?>
            <div class="column is-6">
              <div class="content">
                  <?php
                    $media = $attachments[0]->media();
                    if($media):
                      $url = $media->thumbnailUrl('large');
                      $url = str_replace('http:', '', $url);
                      ?>
                        <img src="<?php echo $url;?>" class='u-display-block'>
                    <?php endif;?>
                </div>
            </div>
          <?php endif;?>

      </div>
  </div>
</section>
