<?php
/**
 * @var \Laminas\View\Renderer\PhpRenderer $this
 * @var \Omeka\Api\Representation\SitePageBlockRepresentation $block
 * @var \Omeka\Api\Representation\ItemSetRepresentation[] $itemSets
 * @var string $thumbnailType
 * @var string $showTitleOption
 * @var string $heading
 */

$plugins = $this->getHelperPluginManager();
$thumbnail = $plugins->get('thumbnail');

$defaultThumbnail = $this->assetUrl('thumbnails/default.png', 'Omeka', true);
$defaultThumbnail = '<img src="' . $defaultThumbnail . '"/>';

$filterLocale = (bool) $this->siteSetting('filter_locale_values');
$lang = $filterLocale ? $this->lang() : null;

$summary = $this->pageMetadata('summary');
?>
<style>
    .card-content {
      background-color: rgba(0,0,0,0.36);
  background:linear-gradient(transparent, black);
  padding: 1.5rem;
  bottom: 0;
  position:absolute;
  width: 100%;
  height: 30%;
  transition: transform 250ms;
  transition-property: height;
}
</style>
<section class="section">
    <div class="container">
        <?php foreach ($itemSets as $itemSet):
            $itemSetTitle = $itemSet->displayTitle();
            $itemSetDescription = $itemSet->displayDescription();
            $itemSetId = $itemSet->id();
            $items = $this->api()->search("items", ["item_set_id" => $itemSetId])->getContent();
            $i=0;
        ?>
        <div class="arrow-left"></div>
        <h1 class="title is-3 is-family-secondary"><?php echo $heading;?></h1>

        <div class="column is-12">
                    <?php echo $summary; ?>
            </div>
        <div class="columns" style="flex-wrap:wrap;padding-top:1em;">

            
                <?php foreach($items as $item):
                    $url = $item->url();
                    $media = $item->media();
                    if($media):
                      $thumbnail = $media[0]->thumbnailUrl('large');                        
                      $imagesize = getimagesize($media[0]->originalUrl());
                      $width = $imagesize[0];
                      $height = $imagesize[1];
                    endif;
                    // if($summary):
                    //   $body = $summary;
                    // else:
                    //   $body = $item->displayDescription();
                    // endif;
                    $body = false;
                    
                ?>
                <div class="column is-4" onclick="moreInfo(<?php echo $i;?>,<?php echo $width;?>,<?php echo $height;?>)" style="cursor:pointer;">
                        
          <div class="card equal-height card-hover-<?php echo $i;?>" <?php if($body):?>onpointerenter="showCardContent(<?php echo $i;?>)<?php endif;?>";>              
            <div class="bg-block" style="background:url(<?php echo  $thumbnail;?>) no-repeat center 20%;background-color:#aaa;background-size: cover; aspect-ratio:1/1;">
            <div class="overlay"></div>

            <div class="card-content" id="card-<?php echo $i;?>">
              <div class="content">
              <div class="card-top">
              <h3 class="title is-5 is-family-secondary has-text-white" id="title-<?php echo $i;?>" title="<?php echo $item->displayTitle();?>" style="white-space:nowrap;overflow:hidden;text-overflow:ellipsis;">
                  <?php echo $item->displayTitle();?>
              </h3>
            </div>
            <!-- <?php if($body):?>
            <div class="is-hidden has-text-white" id="body-<?php echo $i;?>">
                <?php if ($body): ?>
                  <?php
                    if(strlen($body) > 200):
                      $body = substr($body, 0, 200);
                      $body = substr($body, 0, strrpos($body, ' ')).' ...';
                    endif;
                  ?>
                    <?php echo $body; ?>
                <?php endif; ?>
                </div>
                <?php endif;?> -->
              </div>
            </div>
            </div>
          </div>
        
        </div>
                <?php $i++;?>
                <?php endforeach;?>
        </div>
        <?php endforeach;?>
    </div>
</section>

<?php $a=0;?>
<?php foreach($items as $item):
$media = $item->media();?>
<?php 
if($media[0]):
$imagesize = getimagesize($media[0]->originalUrl());
$width = $imagesize[0];
$height = $imagesize[1];
endif;
?>
<div class="modal" id="modal-<?php echo $a;?>" style="justify-content:center;z-index:31;cursor:zoom-in;" <?php if($media[0]):?>onclick="enlargeImage(<?php echo $a?>,<?php echo $width;?>,<?php echo $height;?>);"<?php endif;?>>
    <div class="modal-background"></div>
    <div class="modal-content">    
        <div class="container" style="background-color: aliceblue;width: fit-content;">
          <?php if($media):?>
        <img id="img-<?php echo $a;?>" src="<?php echo $media[0]->originalUrl(); ?>" style="height:93vh;">
          <?php endif;?>
        <div class="column">
        <?php echo $item->displayValues();?>
        <?php if($media):?>
          <div class="has-text-right">
            <a href="<?php echo $media[0]->originalUrl(); ?>" class="button is-warning" style="background-color:#e29ca7;color:aliceblue;font-weight:bold;" download="<?php echo $item->displayTitle();?>">Download</a>
          </div>
        <?php endif;?>
        </div>
        </div>
    </div>
    <button class="modal-close is-large" aria-label="close" onclick="closeModal();"></button>
</div>
<?php $a++;?>
<?php endforeach;?>

<script>
    function moreInfo(x,y,z) {
        let id = '#modal-' + x;
        $( id ).css("cursor","zoom-in");
        $( id ).addClass("is-active");

        let html = '#html'
        $( html ).css("overflow-y","hidden");

        let imgi = 'img-' + x;
        let img = document.getElementById(imgi);
        let contain = document.getElementById(imgi).parentElement;
        let ratio = img.clientWidth / img.clientHeight;
        let width = 'calc(93vh * ' + ratio + ')';
        let windowH = window.innerHeight * 0.93;

        console.log('Height:' + z + 'Window:' + windowH);

        if(z > windowH){
          img.style.height = '93vh';
          contain.style.width = width;
        } else {
          img.style.height = 'auto';
          contain.style.width = y + 'px';
        }
    }
    function enlargeImage(x,y,z){
        let imgi = 'img-' + x;
        let img = document.getElementById(imgi);
        let contain = document.getElementById(imgi).parentElement;
        let width = y + 'px';
        let height = z + 'px';
        let maxWidth = contain.style.maxWidth;

        contain.style.width = width;
        img.style.width = 'auto';
        img.style.height = 'auto'; 

        let cursor = '#modal-' + x;

        $(cursor).css("cursor","unset");
    }

    function closeModal(){
        let modal = '.modal';
        let html = '#html'
        $( modal ).removeClass("is-active");
        $( html ).css("overflow-y","unset");
    }
    
    function showCardContent(x){
    let id = '#card-' + x;
    let hover = '.card-hover-' + x;
    let idtitle = '#title-' + x;
    let idbody = '#body-' + x;
    $(hover).hover(function(){
        $( id ).css("height","100%");
        $( idtitle ).addClass("is-hidden");
        $( idbody ).removeClass( "is-hidden" );
    }, function() {
        $( idtitle ).removeClass( "is-hidden" );
        $( id ).css("height","30%");
        $( idbody ).addClass( "is-hidden" );
    })
    }
</script>