<?php
/**
 * @var \Laminas\View\Renderer\PhpRenderer $this
 * @var \Omeka\Api\Representation\SitePageBlockRepresentation $block
 * @var \Omeka\Api\Representation\ItemSetRepresentation[] $itemSets
 * @var string $thumbnailType
 * @var string $showTitleOption
 * @var string $heading
 */

$plugins = $this->getHelperPluginManager();
$thumbnail = $plugins->get('thumbnail');

$defaultThumbnail = $this->assetUrl('thumbnails/default.png', 'Omeka', true);
$defaultThumbnail = '<img src="' . $defaultThumbnail . '"/>';

$filterLocale = (bool) $this->siteSetting('filter_locale_values');
$lang = $filterLocale ? $this->lang() : null;

$summary = $this->pageMetadata('summary');
?>
<style>
    .card-content {
  background-color: rgba(0,0,0,0.36);
  padding: 1.5rem;
  bottom: 0;
  position:absolute;
  width: 100%;
  height: 30%;
  transition: transform 250ms;
  transition-property: height;
}
</style>
<section class="section">
    <div class="container">
        <?php foreach ($itemSets as $itemSet):
            $itemSetTitle = $itemSet->displayTitle();
            $itemSetDescription = $itemSet->displayDescription();
            $itemSetId = $itemSet->id();
            $items = $this->api()->search("items", ["item_set_id" => $itemSetId])->getContent();
            $i=0;
        ?>
        <div class="arrow-left"></div>
        <h1 class="title is-3 is-family-secondary"><?php echo $heading;?></h1>

        <div class="column is-12">
                    <?php echo $summary; ?>
            </div>
        <div class="columns" style="flex-wrap:wrap;padding-top:1em;">

            
                <?php foreach($items as $item):
                    $url = $item->url();
                    $media = $item->media();
                    if($media):
                    $thumbnail = $media[0]->thumbnailUrl('large');
                    endif;
                    if($summary):
                      $body = $summary;
                    else:
                      $body = $item->displayDescription();
                    endif;
                    
                ?>
                <div class="column is-4" onclick="moreInfo(<?php echo $i;?>)" style="cursor:pointer;">
                        
          <div class="card equal-height card-hover-<?php echo $i;?>" <?php if($body):?>onpointerenter="showCardContent(<?php echo $i;?>)<?php endif;?>";>              
            <div class="bg-block" style="background:url(<?php echo  $thumbnail;?>) no-repeat center 20%;background-color:#aaa;background-size: cover; min-height:250px;">
            <div class="overlay"></div>

            <div class="card-content" id="card-<?php echo $i;?>">
              <div class="content">
              <div class="card-top">
              <h3 class="title is-5 is-family-secondary has-text-white" id="title-<?php echo $i;?>" title="<?php echo $item->displayTitle();?>" style="white-space:nowrap;overflow:hidden;text-overflow:ellipsis;">
                  <?php echo $item->displayTitle();?>
              </h3>
            </div>
            <?php if($body):?>
            <div class="is-hidden has-text-white" id="body-<?php echo $i;?>">
                <?php if ($body): ?>
                  <?php
                    if(strlen($body) > 200):
                      $body = substr($body, 0, 200);
                      $body = substr($body, 0, strrpos($body, ' ')).' ...';
                    endif;
                  ?>
                    <?php echo $body; ?>
                <?php endif; ?>
                </div>
                <?php endif;?>
              </div>
            </div>
            </div>
          </div>
        
        </div>
                <?php $i++;?>
                <?php endforeach;?>
        </div>
        <?php endforeach;?>
    </div>
</section>

<?php $a=0;?>
<?php foreach($items as $item):
$media = $item->media();?>
<div class="modal" id="modal-<?php echo $a;?>" style="justify-content:center;z-index:31;" onclick="closeModal();">
    <div class="modal-background"></div>
    <div class="modal-content">    
        <div class="container" style="background-color: aliceblue;width: fit-content;">
          <?php if($media):?>
        <img src="<?php echo $media[0]->originalUrl(); ?>">
          <?php endif;?>
        <div class="column">
        <?php echo $item->displayValues();?>
        <?php if($media):?>
          <div class="has-text-right">
            <a href="<?php echo $media[0]->originalUrl(); ?>" class="button is-warning" download="<?php echo $item->displayTitle();?>">Download</a>
          </div>
        <?php endif;?>
        </div>
        </div>
    </div>
    <button class="modal-close is-large" aria-label="close"></button>
</div>
<?php $a++;?>
<?php endforeach;?>

<script>
    function moreInfo(x) {
        let id = '#modal-' + x;
        $( id ).addClass("is-active");
    }
    function closeModal(){
        let modal = '.modal';
        $( modal ).removeClass("is-active");
    }
    function showCardContent(x){
    let id = '#card-' + x;
    let hover = '.card-hover-' + x;
    let idtitle = '#title-' + x;
    let idbody = '#body-' + x;
    $(hover).hover(function(){
        $( id ).css("height","100%");
        $( idtitle ).addClass("is-hidden");
        $( idbody ).removeClass( "is-hidden" );
    }, function() {
        $( idtitle ).removeClass( "is-hidden" );
        $( id ).css("height","40%");
        $( idbody ).addClass( "is-hidden" );
    })
    }
</script>