<?php
/**
 * @var \Laminas\View\Renderer\PhpRenderer $this
 * @var string $heading
 * @var array $links
 */

$plugins = $this->getHelperPluginManager();
$escape = $plugins->get('escapeHtml');
$escapeAttr = $plugins->get('escapeHtmlAttr');
?>
<section class="section links-section">
    <div class="container block links">
        <ul class="list-links">
            <?php foreach ($links as $url => $label): ?>
                <li style="padding-bottom:1.5em;">
                    <a href="<?= $escapeAttr($url) ?>"<?php if (filter_var($url, FILTER_VALIDATE_URL)): ?> target="_blank"<?php endif; ?>>
                        <button class="arrow bouncy-button"><?= $escape($label) ?></button>
                    </a>
                </li>
            <?php endforeach; ?>
        </ul>
    </div>
</section>
