<?php
/**
 * @var \Laminas\View\Renderer\PhpRenderer $this
 * @var string $heading
 * @var array $links
 */

$plugins = $this->getHelperPluginManager();
$escape = $plugins->get('escapeHtml');
$escapeAttr = $plugins->get('escapeHtmlAttr');
?>
<style>
    .colour-button:hover {
        box-shadow: unset !important;
        transform:translateX(-5px);
        transition: all 1s ease;
    }
    .colour-button {
        transition: all 1s ease;
    }
</style>
<div class="container block links">
    <?php if (!empty($heading)): ?>
    <h2><?= $escape($heading) ?></h2>
    <?php endif; ?>

    <ul class="list-links">
    <?php foreach ($links as $url => $label): ?>
        <li style="padding-left:2rem;">
            <a href="<?= $escapeAttr($url) ?>"<?php if (filter_var($url, FILTER_VALIDATE_URL)): ?> target="_blank"<?php endif; ?>>
                <button class="button colour-button" style="box-shadow: #00b7e7 -5px -5px, inset white -5px -5px;background-color: #00b7e7;border-color:black;border-width:3px;"><?= $escape($label) ?></button>
            </a>
        </li>
    <?php endforeach; ?>
    </ul>
</div>
