<!-- overview blocks -->
<style>
  .featured-section .column:first-of-type:hover #feature-1 {
    background-color: #f5e300;
  }
  .featured-section .column:hover #feature-2{
    background-color: #00b7e7;
  }
  .featured-section .column:last-of-type:hover #feature-3{
    background-color: #f0a43d;
  }
  .featured-section .column:first-of-type #feature-1 {
    background-color: #f5e30080;
  }
  .featured-section .column #feature-2{
    background-color: #00b7e780;
  }
  .featured-section .column:last-of-type #feature-3{
    background-color: #f0a43d80;
  }
  .featured-section .column:first-of-type #feature-1 h3 span {
    font-family: Montserrat Bold;
  }
  .featured-section .column #feature-2 h3 span {
    font-family: Montserrat Bold;
  }
  .featured-section .column:last-of-type #feature-3 h3 span {
    border-bottom: 2px solid #f0a43d;
    font-family: Montserrat Bold;
  }
  /* .featured-section .column:last-of-type:hover #feature-3 h3 span {
    border-bottom: 2px solid white;
    color: white;
  } */
</style>
<?php if($attachments):?>
  <section class="section color-section featured-section">
    <div class="container">
      <div class="columns">
          <?php  for($i = 1; $i <= sizeof($attachments); $i++){ ?>
            <?php
                $media = $attachments[$i-1]->media();
                $url = '';
                if($media):
                  if($media->mediaType() == 'text/html'):
                    $url = $media->originalUrl();
                    $url = str_replace('http:', '', $url);
                  else:
                    $url = $media->thumbnailUrl('large');
                    $url = str_replace('http:', '', $url);
                  endif;
                endif;
            ?>
            <div class="column">
            <form id="theme-form<?php echo $i;?>" action="https://slimerfgoed.be/s/kadocerfgoed/page/thema" method="POST">
              <input name="tag" value="<?php echo $block->dataValue('link'.$i);?>" hidden>
              <a type="submit" href="#" onclick="onSubmit(<?php echo $i;?>)">
              <div class="featured-block" style="background:url(<?php echo  $url;?>) no-repeat center 20%;background-color:#f5e300;background-size: cover;border-top-right-radius:4px;border-top-left-radius:4px;">
                <div class="overlay"></div>
              </div>
              <div class="featured-content" id="feature-<?php echo $i;?>" style="border-bottom-right-radius:4px; border-bottom-left-radius:4px;">
                  <!-- make whole card clickable -->
                  <!--<div class="content-type is-size-7">
                    Content
                  </div>-->
                  <h3 class="title is-3 is-family-secondary">
                      <span><?php echo $block->dataValue('title'.$i);?></span>
                  </h3>
                  <p class="subtitle is-5"><?php echo $block->dataValue('text'.$i);?></p>

                  <?php if($block->dataValue('link'.$i)):?>
                      <div class="link is-family-secondary"><a>Lees meer</a></div>
                  <?php endif;?>
              </div>
              </a>
              </form>
              <?php if($i == 1 && sizeof($attachments) == 4):?>
              <?php else:?>
                </div>
              <?php endif;?>
          <?php } ?>
        </div>
    </div>
</section>
<?php else:?>
  <p>
    Om dit blok te gebruiken moet je 3 afbeeldingen (attachments) selecteren.
  </p>
<?php endif;?>

<script>
     function onSubmit(x) {
     document.getElementById("theme-form" + x).submit();
   }
</script>
