<!-- overview blocks -->

<?php if($attachments):?>
  <section class="section color-section featured-section">
    <div class="container">
      <div class="columns">
          <?php  for($i = 1; $i <= sizeof($attachments); $i++){ ?>
            <?php
                $media = $attachments[$i-1]->media();
                $url = '';
                if($media):
                  if($media->mediaType() == 'text/html'):
                    $url = $media->originalUrl();
                    $url = str_replace('http:', '', $url);
                  else:
                    $url = $media->thumbnailUrl('large');
                    $url = str_replace('http:', '', $url);
                  endif;
                endif;
            ?>
            <div class="column">
            <form id="theme-form<?php echo $i;?>" action="https://slimerfgoed.be/s/kadocerfgoed/page/thema" method="POST">
              <input name="tag" value="<?php echo $block->dataValue('link'.$i);?>" hidden>
              <a type="submit" href="#" onclick="onSubmit(<?php echo $i;?>)">

              <div class="card equal-height">              
            <div class="bg-block" style="background:url(<?php echo  $url;?>) no-repeat center 20%;background-color:#aaa;background-size: cover;aspect-ratio:1/1;">
            <div class="overlay"></div>

            <div class="card-content" id="feature-<?php echo $i;?>">
              <div class="content">
              <div class="card-top">
              <h3 class="title is-2 is-family-secondary has-text-white" id="title-<?php echo $i;?>">
              <?php echo $block->dataValue('title'.$i);?>
              </h3>
            </div>
            <div class="has-text-white card-body">
            <h2 class="subtitle is-5 has-text-white"><?php echo $block->dataValue('text'.$i);?></h2>
              </div> 
              </div>
            </div>
            </div>
          </div>
              </a>
              </form>
              <?php if($i == 1 && sizeof($attachments) == 4):?>
              <?php else:?>
                </div>
              <?php endif;?>
          <?php } ?>
        </div>
    </div>
</section>
<?php else:?>
  <p>
    Om dit blok te gebruiken moet je 3 afbeeldingen (attachments) selecteren.
  </p>
<?php endif;?>

<script>
     function onSubmit(x) {
     document.getElementById("theme-form" + x).submit();
   }
</script>
