<!-- overview blocks -->
<?php if($attachments):?>
  <section class="section color-section featured-section">
    <div class="container">
      <div class="columns">
          <?php  for($i = 1; $i <= sizeof($attachments); $i++){ ?>
            <?php
                $media = $attachments[$i-1]->media();
                $url = '';
                if($media):
                  if($media->mediaType() == 'text/html'):
                    $url = $media->originalUrl();
                    $url = str_replace('http:', '', $url);
                  else:
                    $url = $media->thumbnailUrl('large');
                    $url = str_replace('http:', '', $url);
                  endif;
                endif;
            ?>
            <div class="column">

              <a href="<?php echo $block->dataValue('link'.$i);?>">
              <div class="featured-block" style="background:url(<?php echo  $url;?>) no-repeat center 20%;background-color:#7fb5b2;background-size: cover;">
                <div class="overlay"></div>
              </div>
              <div class="featured-content">
                  <!-- make whole card clickable -->
                  <!--<div class="content-type is-size-7">
                    Content
                  </div>-->
                  <h3 class="title is-3 is-family-secondary">
                      <span><?php echo $block->dataValue('title'.$i);?></span>
                  </h3>
                  <p class="subtitle is-5"><?php echo $block->dataValue('text'.$i);?></p>

                  <?php if($block->dataValue('link'.$i)):?>
                      <div class="link is-family-secondary"><a href="<?php echo $block->dataValue('link'.$i);?>">Lees meer</a></div>
                  <?php endif;?>
              </div>
              </a>
              <?php if($i == 1 && sizeof($attachments) == 4):?>
              <?php else:?>
                </div>
              <?php endif;?>
          <?php } ?>
        </div>
    </div>
</section>
<?php else:?>
  <p>
    Om dit blok te gebruiken moet je 3 afbeeldingen (attachments) selecteren.
  </p>
<?php endif;?>
