<?php
$this->headLink()->appendStylesheet($this->assetUrl('vendor/leaflet/leaflet.css', 'Mapping'));
$this->headScript()->appendFile($this->assetUrl('vendor/leaflet/leaflet.js', 'Mapping'));
$this->headLink()->appendStylesheet($this->assetUrl('vendor/leaflet.draw/leaflet.draw.css', 'Mapping'));
$this->headScript()->appendFile($this->assetUrl('vendor/leaflet.draw/leaflet.draw.js', 'Mapping'));
$this->headScript()->appendFile($this->assetUrl('vendor/leaflet.providers/leaflet-providers.js', 'Mapping'));
$this->headLink()->appendStylesheet($this->assetUrl('vendor/leaflet.geosearch/assets/css/leaflet.css', 'Mapping'));
$this->headScript()->appendFile($this->assetUrl('vendor/leaflet.geosearch/dist/bundle.min.js', 'Mapping'));
$this->headScript()->appendFile($this->assetUrl('js/mapping-form.js', 'Mapping'));
$this->headScript()->appendFile($this->assetUrl('js/control.opacity.js', 'Mapping'));
$this->headScript()->appendFile($this->assetUrl('js/control.fit-bounds.js', 'Mapping'));
$this->headScript()->appendFile($this->assetUrl('js/control.default-view.js', 'Mapping'));

$mapping = null;
$markers = [];
$itemMedia = [];

if(isset($resource)){
    $item = $resource;
    $pdf = "/themes/kapellen/asset/docs/Handleiding_Kaarttoepassing_ContributorEdit.pdf";
}else{
    $pdf = "/themes/kapellen/asset/docs/Handleiding_Kaarttoepassing_ContributorAdd.pdf";
}

if (isset($item)) {
    $mapping = $this->api()
        ->searchOne('mappings', ['item_id' => $item->id()])->getContent();
    $markers = $this->api()
        ->search('mapping_markers', ['item_id' => $item->id()])->getContent();
    $itemMedia = $item->media();
}
?>
<fieldset id="mapping-section">
    <h4 class="label" style="font-weight:bold;margin-top:1rem;font-size:1.1rem;">Op de kaart</h4>                                       
    <a href="<?php echo $pdf;?>">Bekijk de handleiding</a><br><br>
    <div id="mapping-map" style="height:500px;"
        data-mapping="<?php echo $this->escapeHtml(json_encode($mapping)); ?>"
        data-markers="<?php echo $this->escapeHtml(json_encode($markers)); ?>"
    ></div>
   
    <div id="mapping-form">
        <input type="hidden" name="o-module-mapping:mapping[o:id]">
        <input type="hidden" name="o-module-mapping:mapping[o-module-mapping:bounds]" value="">
    </div>
</fieldset>
