<?php
/*
 * Copyright BibLibre, 2016
 * Copyright Daniel Berthereau, 2017-2020
 *
 * This software is governed by the CeCILL license under French law and abiding
 * by the rules of distribution of free software.  You can use, modify and/ or
 * redistribute the software under the terms of the CeCILL license as circulated
 * by CEA, CNRS and INRIA at the following URL "http://www.cecill.info".
 *
 * As a counterpart to the access to the source code and rights to copy, modify
 * and redistribute granted by the license, users are provided only with a
 * limited warranty and the software's author, the holder of the economic
 * rights, and the successive licensors have only limited liability.
 *
 * In this respect, the user's attention is drawn to the risks associated with
 * loading, using, modifying and/or developing or reproducing the software by
 * the user in light of its specific status of free software, that may mean that
 * it is complicated to manipulate, and that also therefore means that it is
 * reserved for developers and experienced professionals having in-depth
 * computer knowledge. Users are therefore encouraged to load and test the
 * software's suitability as regards their requirements in conditions enabling
 * the security of their systems and/or data to be ensured and, more generally,
 * to use and operate it in the same conditions as regards security.
 *
 * The fact that you are presently reading this means that you have had
 * knowledge of the CeCILL license and that you accept its terms.
 */

/**
 * @var \Zend\View\Renderer\PhpRenderer $this
 * @var \Omeka\Api\Representation\SiteRepresentation $site
 * @var \Search\Query $query
 * @var \Search\Response $response
 * @var array $sortOptions
 * @var array $facets
 * @var bool $isPartial Allow to use this partial in admin board when true.
 */
 $plugins = $this->getHelperPluginManager();
 $translate = $plugins->get('translate');
 $translatePlural = $plugins->get('translatePlural');
 $assetUrl = $plugins->get('assetUrl');
 $partial = $plugins->get('partial');

$isPartial = !$site;
$skipFormAction = !empty($skipFormAction);

// Used in case of a redirect of item-set/show to search, when used like item/browse.
$itemSetId = $this->params()->fromRoute('item-set-id');

$this->headLink()->appendStylesheet($assetUrl('css/search.css', 'Search'));
$this->headScript()->appendFile($assetUrl('js/search.js', 'Search'), 'text/javascript', ['defer' => 'defer']);

$types = array(
  'Slim erfgoed - Tool' => 'Tools',
  'Slim erfgoed - Organisatie' => 'Organisaties',
  'Slim erfgoed - Project' => 'Projecten',
  'Slim erfgoed - Leermiddel' => 'Leermiddelen',
  'Slim erfgoed - Activiteit' => 'Activiteiten',
  'Slim erfgoed - Schoolerfgoed' => 'Schoolerfgoed',
  'Slim erfgoed - School' => 'Scholen',
  'Slim erfgoed - Activiteit' => 'Activiteiten'
);

$texts = array(
  'Tools' => 'De tools die je hier terugvindt helpen je op weg bij de zorg voor en het werken met je schoolerfgoed worden hier samengebracht.  Het kan gaan om leerplannen, handleidingen, selectielijsten, databanken, websites, wetenschappelijke artikelen... Zoek en vind hier een antwoord op je vraag.',
  'Organisaties' => 'Tal van organisaties spannen zich in om scholen te ondersteunen en te begeleiden bij de bewaring en het inzetten van hun erfgoed.  Dat kan gaan om lokale, regionale en landelijke erfgoedorganisaties.  Ook de overheden doen hun duit in het zakje.  Hieronder vind je een niet-exhaustieve lijst van organisaties.  Klik op een organisaties om te weten te komen wat ze voor jou kunnen betekenen. ',
  'Projecten' => 'Scholen en erfgoedorganisaties vinden hen elkaar sedert een twintigtal jaren op een projectmatige basis rond schoolerfgoed.  Op deze pagina krijg je een inspirerend overzicht.  Ook de proeftuinen van slimerfgoed kan je hier terugvinden.',
  'Leermiddelen' => 'Je wilt met schoolerfgoed aan de slag in de klas.  Je bent op zoek naar materiaal dat  je rechtstreeks in de klas kan gebruiken? Doorzoek het aanbod voor basis- en secundair onderwijs hier.',
  'Activiteiten' => 'Een scholenfietsroute, een jubileumexpo, een vormingsdag, een vast aanbod.  Zoek hier welke activiteiten en aanbod je kan meepikken.  Interessant voor scholen en erfgoedorganisaties.',
  'Inspiratie' => 'Wil je met schoolerfgoed aan de slag in de school of de klas?  Wil je een participatief project uit de grond stampen?  Of heb je ambities rond een uitwisselingsproject op school?  Hier vind je inspirerende projecten, handige leermiddelen een het aanbod aan activiteiten.',
  'Schoolerfgoed' => 'Schoolerfgoed is zeer gevarieerd: van een beschermd patrimonium over een karakteristieke buitenaanleg, tot een bijzondere kunst- en beeldencollectie.  Ook een wereldbol, kroontjespen, een venndiagram, digitale agenda, de Honderd Dagenviering of de verhalen van en over leerkrachten behoren tot het collectieve geheugen van een generatie.',
  'Scholen' => 'Je bent een school met erfgoed als je over een waardevol of beschermd patrimonium beschikt. Je bent ook een school met erfgoed als er ter plaatse of bij een organisatie erfgoed bewaard wordt. Dat kan een archief zijn, een foto- of handboekencollectie of markante voorwerpen. Hieronder vind je een niet-exhaustieve lijst van scholen met erfgoed. Klik op een school om te weten te komen over wat voor erfgoed het gaat en waar het zich bevindt.',
);

$subtype = $searchPage->name();
if($searchPage->name() == 'Zoek op thema'):
  $subtype = 'op thema';
endif;
$filters = $query->getFilters();
if(isset($filters['resource_template_id'])):
  foreach($filters['resource_template_id'] as $template):
    $subtype =  $types[$template];
  endforeach;
endif;

?>
<section class="section breadcrumb-section">
  <div class="container">
    <nav class="breadcrumb" aria-label="breadcrumbs">
      <ul>
        <li><a href="/">Home</a></li>
        <?php if($searchPage->name() == 'Zoek op thema'):?>
          <li><a href="<?php echo '/page/schoolerfgoed';?>">Schoolerfgoed</a></li>
          <li><a href="<?php echo '/item-set/browse';?>">Thema's</a></li>
        <?php else:?>
          <li><a href="<?php echo '/page/'.strtolower($searchPage->name());?>"><?php echo $searchPage->name();?></a></li>
        <?php endif;?>
        <li><?php echo 'Zoek '.strtolower($subtype); ?></li>
      </ul>
    </nav>
  </div>
</section>

<?php if (empty($isPartial)): ?>
<section class="section">
  <div class="container" role="main">

  <?php endif; ?>
  <?php if ($itemSetId): ?>
      <?php $itemSet = $this->api()->read('item_sets', ['id' => $itemSetId])->getContent(); ?>
      <?php $this->vars()->offsetSet('itemSet', $itemSet); ?>
      <?php $this->vars()->offsetSet('resourceType', 'item_sets'); // TODO Check if really needed. ?>
      <?php $this->htmlElement('body')->appendAttribute('class', 'search-page item-set resource browse'); ?>
      <?= $this->pageTitle($itemSet->displayTitle(), 2) ?>
      <h2 class="title is-2 is-family-secondary"><?= $translate('Item set') ?></h2>
      <div class="metadata">
          <?= $itemSet->displayValues() ?>
      </div>
      <div class="item-set-items">
          <h2 class="title is-3 is-family-secondary"><?= $translate('Items') ?></h2>
      </div>

  <?php else: ?>

      <?php $this->htmlElement('body')->appendAttribute('class', 'search-page resource browse'); ?>


      <?php
        if(isset($filters['item_set_id'])):
          $id = $filters['item_set_id'][0];
          $res = $this->api()->read('item_sets', $id);
          $set = $res->getContent();
        endif;
        $titel = $searchPage->name();
        if(isset($filters['resource_template_id']) && $searchPage->name() != 'Zoek op thema'):?>
          <h2 class="subtitle is-1">
          <?php foreach($filters['resource_template_id'] as $template):?>
            <?php if($template == "Slim erfgoed - Organisatie"):?>
            
              <?php if(isset($filters['organisatie:ondersteuningsaanbod'])):?>  
                
                <?php if($filters['organisatie:ondersteuningsaanbod'][0] == 'Ja'): ?>
                  
                  <?php echo $types[$template];?> met ondersteuningsaanbod
                <?php endif;?>
              <?php else:?>
                <?php echo $types[$template];?>
              <?php endif;?>
            <?php else:?>
              <?php echo $types[$template];?>
            <?php endif;?>
            <?php $titel = $types[$template];?>
          <?php endforeach;?>
          </h2>
        <?php elseif(isset($filters['item_set_id'])):?>
          <h2 class="subtitle is-1">
          <?php echo 'Thema '.$set->value('dcterms:title');?>
          </h2>
        
        <?php else:?>
            <h2 class="subtitle is-1"><?php echo $translate($searchPage->name()); ?></h2>
        <?php endif;?>

        <?php if($searchPage->name() != 'Zoek op thema'):?>
            <div class="columns">
              <div class="column is-9">
                <div class="content show-text">
                  <?php echo $texts[$titel];?>
                </div>
              </div>
            </div>
        <?php elseif(isset($filters['item_set_id'])):?>
            <div class="columns">
              <div class="column is-9">
                <div class="content show-text">
                    <?php echo $set->value('dcterms:description');?>
                </div>
              </div>
            </div>
        <?php endif;?>
  <?php endif; ?>
  <?php
    if($searchPage->name() == 'Zoek op thema'):
      $zoek = "Zoek in alle thema's";
    else:
      $zoek = "Zoek";
    endif;
  ?>
  <div class="content">
    <form class="has-icons-right" action="" id="search-form">
      <div class="field has-addons">
        <div class="control">
          <input class="input is-medium" type="text" name="q" id="q" placeholder="<?php echo $zoek;?>" value="<?php echo $query->getQuery();?>"   aria-label="<?php echo $translate('Search'); ?>">
          <input name="sort" type="hidden" value="<?php echo $query->getSort();?>" />
        </div>
        <div class="control">
          <a class="button is-info is-medium">
            <span class="icon is-large">
              <i class="fas fa-search"></i>
            </span>
          </a>
        </div>
      </div>
    </form>
  </div>
</div>
</section>
<section class="section results">
  <div class="container is-fluid">
    <?php //echo $query->getQuery().'&sort='.$query->getSort().'&'.json_encode($query->getFilters());?>
  <?php if (isset($response)): ?>
  <div class="columns">
    <?= $partial('search/facets', ['searchPage' => $searchPage, 'query' => $query, 'response' => $response]) ?>

      <div class="column is-three-quarter">
          <?php if ($response->getTotalResults()): ?>
            <?= $partial('search/results-header', [
                'searchPage' => $searchPage,
                'query' => $query,
                'response' => $response
            ]) ?>
              <?php $itemSetsCount = $response->getResourceTotalResults('item_sets'); ?>
            <?= $partial('search/resource-list', [
                'site' => $site,
                'title' => sprintf($translatePlural('%s item set', '%s item sets', $itemSetsCount), $itemSetsCount),
                'response' => $response,
                'resourceName' => 'item_sets',
            ]) ?>
              <?php $itemsCount = $response->getResourceTotalResults('items'); ?>
              <?= $partial('search/resource-list', [
                  'site' => $site,
                  'title' => sprintf($translatePlural('%s item', '%s items', $itemsCount), $itemsCount),
                  'response' => $response,
                  'resourceName' => 'items',
              ]) ?>

              <?= $partial('search/results-footer', [
                  'query' => $query,
                  'response' => $response,
                  'sortOptions' => $sortOptions,
              ]) ?>

          <?php elseif (empty($query) && empty($itemSetId)): ?>

              <div class="noresults"><?= $translate('Fill a query and get results.') ?></div>

          <?php elseif (empty($query) && $itemSetId): ?>

              <div class="noresults"><?= $translate('This item set has no items.') ?></div>

          <?php else: ?>

              <div class="noresults"><?= $translate('Your query returned no results') ?></div>

          <?php endif; ?>

      </div>

  </div>

  <?php else: ?>

    <div class="search-results-wrapper">
        <div class="search-results">
            <div class="noresults"><?= $translate('An error occured and your query returned no results.') ?></div>
        </div>
    </div>

  <?php endif; ?>

  <?php if (empty($isPartial)): ?>
    </div>
  <?php endif; ?>
  </div>
</section>
