<?php
/**
 * @var \Laminas\View\Renderer\PhpRenderer $this
 * @var \Omeka\Api\Representation\SiteRepresentation $site
 * @var \AdvancedSearch\Response $response
 * @var string $resourceName
 * @var string $title
 */

$resources = $response->getResources($resourceName);

// A check is done: when page is not first, the resources may be empty even with results.
if (!$resources) return;

$plugins = $this->getHelperPluginManager();
$translate = $plugins->get('translate');
$hyperlink = $plugins->get('hyperlink');
$assetUrl = $plugins->get('assetUrl');
$escape = $plugins->get('escapeHtml');
$thumbnailHelper = $plugins->get('thumbnail');

$setting = $plugins->get($site ? 'siteSetting' : 'setting');

$filterLocale = (bool) $setting('filter_locale_values');
$lang = $this->lang();

$headingTerm = $setting('browse_heading_property_term');
$bodyTerm = $setting('browse_body_property_term');
if ($headingTerm) {
    $headingOptions = [
        'default' => $translate('[Untitled]'),
        'lang' => ($filterLocale ? [$lang, ''] : null)
    ];
} else {
    $headingOptions = $filterLocale ? [$lang, ''] : null;
}
if ($bodyTerm) {
    $bodyOptions = ['lang' => ($filterLocale ? [$lang, ''] : null)];
} else {
    $bodyOptions = $filterLocale ? [$lang, ''] : null;
}

$defaultThumbnail = '<img src="' . $assetUrl('thumbnails/default.png', 'Omeka') . '" title="' . $translate('No media') . '"/>';
?>


<div class="columns is-multiline" style="align-items:strech;">
    <?php /** @var \Omeka\Api\Representation\AbstractResourceEntityRepresentation $resource */
    foreach ($resources as $resource):
        $resourceType = $resource->resourceName();
        $mediaUrl = $resource->thumbnailDisplayUrl('square');        
        if(!$mediaUrl):
            $mediaUrl= "/application/asset/thumbnails/default.png?v=3.2.0";
        endif;    
               
        $heading = $headingTerm ? $resource->value($headingTerm, $headingOptions) : $resource->displayTitle(null, $headingOptions);
        $body = $bodyTerm ? $resource->value($bodyTerm, $bodyOptions) : $resource->displayDescription(null, $bodyOptions);
        $template = $resource->resourceTemplate();
        if($template):
            $type = $template->label();
        else:
            $type = "";
        endif;
    ?>

    <div class="column is-3 resource-thumbnail resource <?= $resourceType ?>" >
        <div class="">
            <a class="resource-link" href="https://kapelletjes.be/item/<?php echo $resource->id();?>"><img src="<?php echo $mediaUrl;?>"></a>
        </div>   
        <div class="resource-metadata-grid">
            <h4 style="margin:0.3rem 0;" class="title is-4 font-family-secondary"> <a href="https://kapelletjes.be/item/<?php echo $resource->id();?>"><?php echo $heading;?></a></h4>        
            <?php if($resource->value("locatie:gemeente") || $resource->value("locatie:deelgemeente")):?>
                <h5 style="margin:0.3rem 0;" class="subtitle is-5">
                <?php if($resource->value("locatie:gemeente")):
                    echo $resource->value("locatie:gemeente");
                endif;
                if($resource->value("locatie:deelgemeente")):
                    if($resource->value("locatie:deelgemeente")->asHtml() != $resource->value("locatie:gemeente")->asHtml()):
                        echo ", ".$resource->value("locatie:deelgemeente");
                    endif;
                endif;?>       
                </h5>
            <?php endif;?>    
        </div>
    </div> 
    <div class="column is-8 resource-metadata">
        <div class="white-box">
            <h4 style="margin:0.3rem 0;" class="title">
            <a href="https://kapelletjes.be/item/<?php echo $resource->id();?>"><?php echo $heading;?></a>                      
            </h4>
        
            <?php if($resource->value("locatie:gemeente") || $resource->value("locatie:deelgemeente")):?>
                <h5 style="margin:0.3rem 0;font-size:1.1rem;" class="subtitle is-5">
                <?php if($resource->value("locatie:gemeente")):
                    echo $resource->value("locatie:gemeente");
                endif;

                if($resource->value("locatie:deelgemeente")):
                    if($resource->value("locatie:deelgemeente")->asHtml() != $resource->value("locatie:gemeente")->asHtml()):
                    echo ", ".$resource->value("locatie:deelgemeente");
                    endif;
                endif;?>                     
                <?php if($resource->value("schema:dateCreated")):?>
                    <?= ", ".$resource->value("schema:dateCreated");?>
                <?php endif;?>  
                </h5>
            <?php endif;?>    
                
            <div class="description">
                <?php if ($resource->displayDescription()): ?>
                    <?php $body = $resource->displayDescription();?>   
                    <p>
                        <?php $trunc = implode(" ", array_slice(explode(" ", $body), 0, 21)); ?>
                        <?php if(strlen($body) != strlen($trunc)):?>
                        <?php echo $trunc.' ...';?>
                        <?php else:?>
                        <?php echo $trunc;?>
                        <?php endif;?>
                    </p>
                <?php endif; ?>
            </div>   
            <?php if($resource->value("schema:creator")):?>
                <div class="creator" style="font-size:0.9rem;margin-top:1rem;">
                    <a style="padding: 0.2rem 0;" href="/s/zorgerfgoed/collecties?facet[schema%3Acreator][]=<?php echo $resource->value("schema:creator");?>"><?php echo $resource->value("schema:creator");?></a>
                </div>
            <?php endif;?>
            <div style="padding-top:1rem;">
                <span>
                    <a href="https://kapelletjes.be/item/<?php echo $resource->id();?>">
                    Alle gegevens
                    <span class="icon is-small">
                        <i class="fas fa-caret-right"></i>
                    </span>
                    </a>
                </span>     
            </div>
        </div>
    </div>

    <?php endforeach; ?>
</div>
