<?php
$escape = $this->plugin('escapeHtml');
$siteTitle = $site->title();
$this->htmlElement('html')->setAttribute('lang', $this->lang());
$this->headMeta()->setCharset('utf-8');
$this->headMeta()->appendName('viewport', 'width=device-width, initial-scale=1');
$this->headTitle($siteTitle)->setSeparator(' · ');
$this->headTitle()->append($this->setting('installation_title', 'Omeka S'));
$this->headLink()->prependStylesheet($this->assetUrl('css/style.min.css'));
//$this->headLink()->prependStylesheet($this->assetUrl('css/iconfonts.css', 'Omeka'));
//$this->headLink()->prependStylesheet('//fonts.googleapis.com/css?family=Open+Sans:400,400italic,600,600italic,700italic,700');
$this->headScript()->prependFile($this->assetUrl('js/default.js'));
$this->headScript()->prependFile($this->assetUrl('js/slick.js'));
$this->headScript()->prependFile($this->assetUrl('js/clamp.min.js'));
$this->headScript()->prependFile($this->assetUrl('js/global.js', 'Omeka'));
$this->headScript()->prependFile($this->assetUrl('vendor/jquery/jquery.min.js', 'Omeka'));
$this->trigger('view.layout');
$userBar = $this->userBar();

$url = $this->serverUrl(true);
if (strpos($url, 'page/home') !== false) {
    $home = false;
}else{
  $home = false;
}
?>
<?php echo $this->doctype(); ?>
<?php echo $this->htmlElement('html'); ?>
    <head>
        <?php echo $this->headMeta(); ?>
        <?php echo $this->headTitle(); ?>
        <?php echo $this->headLink(); ?>
        <?php echo $this->headStyle(); ?>
        <?php echo $this->headScript(); ?>
        <script src="https://kit.fontawesome.com/582fb8c29f.js" crossorigin="anonymous"></script>
        <link href="https://fonts.googleapis.com/css2?family=Source+Sans+Pro:wght@300;400;600;700&family=Raleway:ital,wght@0,300;0,400;0,500;0,600;1,300;1,400;1,500;1,600&display=swap" rel="stylesheet">
        <script src="https://unpkg.com/colcade@0/colcade.js"></script>
		<!-- Global site tag (gtag.js) - Google Analytics -->
		<script async src="https://www.googletagmanager.com/gtag/js?id=UA-208068755-1"></script>
		<script>
		  window.dataLayer = window.dataLayer || [];
		  function gtag(){dataLayer.push(arguments);}
		  gtag('js', new Date());

		  gtag('config', 'UA-208068755-1');
		</script>
    </head>

    <?php echo $this->htmlElement('body'); ?>
    <?php echo $userBar; ?>
    <?php if(!$home):?>
    <header>
        <nav class="navbar is-white" role="navigation" aria-label="main navigation">
          <div class="container">
          <div class="navbar-brand">
            <a class="navbar-item" href="<?php echo $site->url(); ?>">
              <?php if ($this->themeSetting('logo')): ?>
                  <img src="<?php echo $this->themeSettingAssetUrl('logo'); ?>" alt="<?php echo $escape($siteTitle); ?>" />
              <?php else: ?>
                  <?php echo $escape($siteTitle); ?>
              <?php endif; ?>
            </a>
          </div>
          <div class="navbar-menu">
            <div class="navbar-start">

            </div>
            <div class="navbar-end">
              <div class="navbar-item">
                 <button class="button is-primary" id="showNav">
                    <span class="icon is-small">
                      <i class="fas fa-bars"></i>
                    </span>
                  </button>
                 <button class="button is-primary" id="showSearch">
                    <span class="icon is-small">
                      <i class="fas fa-search"></i>
                    </span>
                  </button>
                </div>
             </div>
          </div>
        </div>
      </nav>
    </header>
    <?php endif;?>
    <div class="over-footer">
      <div class="wrapper">
        <?php echo $this->content; ?>
      </div>
    </div>

    <footer class="footer">
      <section class="footer-top">
        <div class="container">
          <nav class="level">
            <!-- Left side -->
            <div class="level-left">
              <div class="level-item">
                Realisatie van Cultureel Erfgoed Annuntiaten Heverlee, KADOC en LIBIS<br /> met steun van de Vlaamse Overheid
              </div>
              <div class="level-item">
                <img style="height:60px;padding:0 5px;" src="/themes/base/asset/img/vlaanderen.png" />
              </div>
            </div>

            <!-- Right side -->
            <div class="level-right">
              <p class="level-item">
                <ul>
                  <li><a href="/s/start/page/contact">Contact</a></li>
                  <li><a href="/s/start/page/over">Over ons</a></li>
                </ul></p>
              <p class="level-item"></p>
            </div>
          </nav>
          <div class="" style="font-size:0.8rem;max-width:600px;color:#ccc;">
            © slimerfgoed.be All photos and texts on this site are copyright of the respective photographers and webeditor. Unauthorized reproduction without specific written permission is prohibited.
          </div>
        </div>
      </section>
      <section class="footer-bottom">
        <div class="container">
          <nav class="level">
            <!-- Left side -->
            <div class="level-left">

            </div>

            <!-- Right side -->
            <div class="level-right">
              <div class="level-item">
                <a target="_blank" href="https://www.cultureelerfgoedannuntiatenheverlee.be/"><img style="height:60px;padding:0 5px;" src="/themes/base/asset/img/heverlee.png" /></a>
              </div>
              <div class="level-item">
                <a target="_blank" href="https://kadoc.kuleuven.be"><img style="height:40px;padding:0 5px;" src="/themes/base/asset/img/kadoc.PNG" /></a>
              </div>
              <div class="level-item">
                <a target="_blank" href="https://libis.be"><img style="height:40px;padding:0 5px;" src="/themes/base/asset/img/libis_gray.png" /></a>
              </div>
            </div>
          </nav>
        </div>
      </section>
      <?php if ($footerContent = $this->themeSetting('footer')): ?>
      <?php //echo $footerContent; ?>
      <?php endif; ?>
    </footer>

    <div class="search-menu modal">
      <div class="modal-background"></div>
        <div class="modal-content">
          <?php echo $this->partial('common/search-form'); ?>
        </div>
        <button class="search-menu-close modal-close is-large"></button>
     </div>

     <div class="burger-menu modal">
       <div class="modal-background"></div>
         <div class="modal-content">
           <!-- Any other Bulma elements you want -->
           <?php echo $this->partial('common/search-form'); ?>
           <?php
             echo $site->publicNav()->menu()->renderMenu(null, [
                 'maxDepth' => $this->themeSetting('nav_depth') - 1
             ]);
           ?>
         </div>
         <button class="burger-menu-close modal-close is-large"></button>
      </div>
  </body>
  <script>
  $(document).ready(function() {
    // Check for click events on the navbar burger icon
    $("#showNav").click(function() {
        $(".burger-menu").toggleClass("is-active");
    });

    $("#showSearch").click(function() {
      $(".search-menu").addClass("is-active");
    });

    $(".search-menu-close").click(function() {
       $(".search-menu").removeClass("is-active");
    });
    $(".burger-menu-close").click(function() {
       $(".burger-menu").removeClass("is-active");
    });
  });
  </script>
</html>
