<?php
use Laminas\Mail;
use Laminas\Mime\Message as MimeMessage;
use Laminas\Mime\Mime;
use Laminas\Mime\Part as MimePart;
use Laminas\ServiceManager\ServiceLocatorInterface;

$tentoonstellingen = [];
$collecties = [];
$verhalen = [];

foreach($pages as $page):
  if($page->dataValue('type') == 'tentoonstelling'):
    $tentoonstellingen[] = $page;
  elseif($page->dataValue('type') == 'collecties'):
    $collecties[] = $page;
  else:
    $verhalen[] = $page;
  endif;
endforeach;

//$settings = $this->getServiceLocator()->get('Omeka\Settings');
$siteKey = $this->setting('recaptcha_site_key');
$secretKey = $this->setting('recaptcha_secret_key');

$get  = filter_input_array(INPUT_GET, FILTER_SANITIZE_STRING);
$post  = filter_input_array(INPUT_POST, FILTER_SANITIZE_STRING);
?>
<style>
  .select:not(.is-multiple):not(.is-loading)::after{
    border-color: #e29ca7;
  }
</style>

  <div class="container">   

    <div class="columns">
      <div class="column is-8">
      <?php                
        if($_SERVER['REQUEST_METHOD'] == 'POST' && isset($_POST['vraag'])):
          if(!isCaptchaValid($secretKey)):
            $error = "reCaptcha is niet geldig";
          else:  
            $post  = filter_input_array(INPUT_POST, FILTER_SANITIZE_STRING);
            $error = '';


            $onderwerp = $pages[$post["onderwerp"]]->page()->title();
            $url = '<a href="'. $this->serverUrl() . $pages[$post["onderwerp"]]->page()->url() . '">' . $onderwerp . '</a>';

            
            $message = "<p>Naam: ".$post["naam"]."</p><p>E-mailadres: ".$post["mail"]."</p><p>Onderwerp: ".$url."</p><p>".$post["vraag"];
            $html = new MimePart($message);
            $html->type = Mime::TYPE_HTML;
            $html->charset = 'utf-8';
            $html->encoding = Mime::ENCODING_QUOTEDPRINTABLE;
            $body = new MimeMessage();
            $body->setParts([$html]);


            $name = $post["naam"];
            if (!preg_match("/^[a-zA-Z-' ]*$/",$name)) {
              $error = "Geen geldige naam";
            }

            $email = $post["mail"];
            if (!filter_var($email, FILTER_VALIDATE_EMAIL)) {
              $error = "Geen geldig e-mailadres";
            }
          endif;  
         
          
          if(!$error):
            
            $mail = new Mail\Message();
            $mail->setBody($body);
            $mail->setFrom('no-reply-KADOC-Erfgoed@kuleuven.be', $post["naam"]);            
            $mail->addTo("rebecca.vancaeneghem@kuleuven.be", 'Rebecca Van Caeneghem');
            $mail->setSubject("KADOC Erfgoed: ".$onderwerp);

            $transport = new Mail\Transport\Sendmail();
            $transport->send($mail);
            
            ?>
            <article class="message is-success">
              <div class="message-body">
                <strong>Bedankt voor uw bericht!</strong>
              </div>
            </article>   
          <?php else:?>
            <article class="message is-danger">
              <div class="message-body">
                <?php echo $error;?>
              </div>
            </article>
          <?php endif;?> 
        <?php endif;?>  
        <form id="feedback-form" method="post">
          <div class="field">
            <label class="label" for="naam">Naam</label>
            <div class="control">
              <input class="input" type="text" id="naam" name="naam" required placeholder="">
            </div>
          </div>
          <div class="label" class="field">  
            <label for="mail">E-mailadres</label>
            <div class="control">
              <input class="input" type="mail" id="mail" name="mail"required placeholder="">
            </div>
          </div>

          <div class="field">
            <label class="label" for="onderwerp">Waarop wil je reageren?</label>
            <div class="control select">
              <select id="category" name="category" required placeholder="Kies een categorie...">
                <!-- <option value="" disabled selected>Kies een categorie...</option> -->
                <option value="algemeen">Algemeen</option>
                <option value="collectie">Collectie</option>
                <option value="tentoonstelling">Tentoonstelling</option>
                <option value="verhaal">Verhaal</option>
              </select>
            </div>
            <div class="control select">
              <select id="onderwerp" name="onderwerp" required>
                <option value="algemeen" class="algemeen">Algemeen bericht</option>
                <?php foreach($pages as $collectie): ?>
                <option value="<?php echo $collectie->page()->slug();?>" class="<?php echo $collectie->dataValue('type'); ?>"><?php echo $collectie->page()->title() ?></option>
                <?php endforeach;?>
              </select>
            </div>
          </div>
        
          <div class="label" class="field">  
            <label for="vraag">Bericht</label>
            <div class="control">
              <textarea required class="textarea" id="vraag" name="vraag" placeholder=""></textarea>
            </div>
          </div>
          
          <div class="field" style="padding-bottom:1.5em;">  
            <button data-sitekey="<?php echo $siteKey;?>" data-callback='onSubmit' data-action='submit' class="g-recaptcha bouncy-button react" style="background-color: #e29ca7;">Verzenden</button>
          </div>
        </form> 
      </div>  
    </div>  
  </div>
<script>
<?php if (isset($_POST["slug"])):;?>
  <?php $postslug = $_POST["slug"];
  $postcategory = $_POST["type"];
  ?>

postSlugCheck('<?php echo $postslug;?>','<?php echo $postcategory;?>');


<?php unset($_POST["slug"]); 
$_POST["type"];
?>
  <?php endif;?>

function postSlugCheck(x,y){
  let id = '#onderwerp';
  let category = '#category';

  $( id ).val(x);
  $( category ).val(y);
}

   function onSubmit(token) {
     document.getElementById("feedback-form").submit();
   }

   $(document).ready(function () {
      $(document).on('change', '#category', function () {
          var val = $(this).val().toLowerCase();
          $('#onderwerp option').hide().removeAttr("selected");
          $('#onderwerp option.'+val).show();
          $('#onderwerp option.'+val+':first').attr('selected','selected').change();
      });
  });
</script>
<script src='https://www.google.com/recaptcha/api.js?
render=onload
& async defer'>
</script>

<?php 
function isCaptchaValid($secretKey){
    $captcha = isset($_POST['g-recaptcha-response']) ? $_POST['g-recaptcha-response'] : false;

    if (!$captcha) {
        return false;
    }

    $postdata = http_build_query(
        array(
            "secret" => $secretKey,
            "response" => $captcha,
            "remoteip" => $_SERVER["REMOTE_ADDR"]
        )
    );
    $opts = array(
        'http' =>
        array(
            "method"  => "POST",
            "header"  => "Content-Type: application/x-www-form-urlencoded",
            "content" => $postdata
        )
    );
    $context  = stream_context_create($opts);
    $googleApiResponse = file_get_contents("https://www.google.com/recaptcha/api/siteverify", false, $context);

    if ($googleApiResponse === false) {
        return false;
    }

    $googleApiResponseObject = json_decode($googleApiResponse);

    return $googleApiResponseObject->success;
}
?>