<?php
$translate = $this->plugin('translate');
?>
<section class="section carousel-section" style="background:#2f2828;">
  <div class="container">
    <?php if ($this->heading): ?>
      <h2 class="title is-4 is-family-secondary"><?php echo $this->heading; ?></h2>
    <?php endif; ?>

    <?php if($block->dataValue('text')):?>
      <div class="content">
              <?php echo $block->dataValue('text');?>
      </div>
    <?php endif; ?>

    <?php if($this->resources):?>
    <div class="slider">
      <?php
      $headingTerm = $this->siteSetting('browse_heading_property_term', 'dcterms:title');
      $bodyTerm = $this->siteSetting('browse_body_property_term', 'dcterms:description');

      foreach ($this->resources as $resource):
        $heading = $resource->value($headingTerm, ['default' => $translate('[Untitled]')]);
        $body = $resource->value('dcterms:description');
        if($resourceType == 'item-set'):
          $body = $resource->value('dcterms:description');
        endif;
        $type = $resource->resourceTemplate();
        if($type):
          $type= $type->label();
        elseif($resourceType == 'item-set'):
          $type= 'Collection';
        else:
          $type= "Object";
        endif;
      ?>
      <div class="slide">
            <?php
              $mediaurl = "";
              $media = $resource->media();              
              $url = $resource->url();
            ?>

            <div class="slide-container">       
              <div class="relative-slide">
                <?php if($media):?>
                  <img src="<?php echo $media[0]->thumbnailUrl('medium');?>">
                <?php else:?>                  
                  <img src="/collectiewijzer/application/asset/thumbnails/default.png?v=3.1.0">
                <?php endif;?>
               
                <div class="tags">                   
                  <?php if($resource->value("cw:describes_onderwerp")):?>
                    <?php $decs = $resource->value("cw:describes_onderwerp",['all' => true]); ?>
                    <?php $decs_sort = array();?>
                    <?php foreach($decs as $dec):?>
                      <?php $decs_sort[$dec->asHtml()] = $dec;?>
                    <?php endforeach;?>
                    <?php ksort($decs_sort);?>
                    <?php foreach($decs_sort as $dec):?>           
                      <a class="tag is-link is-primary" href='<?php echo "https://collectiewijzer.be/s/collectiewijzer/zoek?facet[cw_describes_onderwerp_ss][]=".$dec->asHtml(); ?>'><?php echo $dec->asHtml();?></a><br>      
                    <?php endforeach?>
                  <?php endif;?>
                </div>
                <div class="slide-content">
                
                <h5 class="title is-6 is-family-secondary">
                    <a href="<?php echo $resource->url(); ?>"><?php echo $resource->value('cw:preferred_labels');?></a>
                </h5>
                
                                  
                <div class="content">
                  <?php $body = $resource->value('dcterms:description');?>
                  <?php if ($body): ?>
                    <?php
                      if(strlen($body) > 200):
                        $body = substr($body, 0, 200);
                        $body = substr($body, 0, strrpos($body, ' ')).' ...';
                      endif;
                    ?>
                    <p>
                      <?php echo $body; ?>
                    </p>
                  <?php endif; ?>
                </div>
              </div>
              </div>
             
          </div>
        </div>
      <?php endforeach; ?>
     
      </div>
      <div class="browse-all has-text-right">
          <a href="https://collectiewijzer.be/s/collectiewijzer/zoek" class="button is-primary is-outlined">
            <?php echo $this->linkText;?>
          </a>
      </div>
    <?php endif;?>
  </div>
</section>
<script>
  $( document ).ready(function() {
    $(".slider").slick({
      centerMode: true,
      centerPadding: '0px',
      slidesToShow: 5,
      responsive: [
        {
          breakpoint: 768,
          settings: {
            arrows: true,
            centerMode: true,
            centerPadding: '40px',
            slidesToShow: 3
          }
        },
        {
          breakpoint: 480,
          settings: {
            arrows: false,
            centerMode: true,
            centerPadding: '40px',
            slidesToShow: 1
          }
        }
      ]
    });  
  });  
</script>  
