

<?php
$translate = $this->plugin('translate');
?>
<style>
.zigzag {
  display: inline-block;
  position: relative;
}

.zigzag:after {
  content: '';
  height: 18px;
  width: 100%;
  position: absolute;
  background: url("https://cldup.com/MiGVGBh-0U.png");
  background-size: 30px;
  top: 35px;
  bottom: 0px;
  left: 0;
}
.card-content {
  background-color: rgba(0,0,0,0.36);
  background:linear-gradient(transparent, black);
  padding: 1.5rem;
  bottom: 0;
  position:absolute;
  width: 100%;
  height: 50%;
  transition: transform 250ms;
  transition-property: height;
}
</style>
<section class="section page-browse-section">
  <div class="container">
    <?php if ($this->heading): ?>
      <div class="arrow-left"></div>
      <h2 class="title is-3 is-family-secondary" style="padding-bottom: 30px;"><?php echo $block->dataValue('heading');?></h2>
    <?php endif; ?>

    <?php if($block->dataValue('text')):?>
      <div class="columns">
        <div class="column is-8">
          <div class="content">
              <?php echo $block->dataValue('text');?>
          </div>
        </div>
      </div>
    <?php endif; ?>

    <div class="columns is-multiline">
      <?php
      $i=0;
      foreach ($pages as $page):
        $heading = $page->page()->title();
        $body = $page->dataValue('summary');
        $i++;
      ?>
      <div class="column is-4">
        <?php
          $asset = $page->dataValue('cover');

          if (!$asset) {
              $mediaurl = "";
          }else{
            try {
                $media = $this->api()->read('assets', ['id' => $asset])->getContent();
                $mediaurl = $media->assetUrl('large');
            } catch (NotFoundException $e) {
                $mediaurl = "";
            }
          }

          $url = $page->page()->url();
        ?>
        <a href="<?php echo $url;?>">
          <div class="card equal-height card-hover-<?php echo $i;?>" onpointerenter="showCardContent(<?php echo $i;?>)";>              
            <div class="bg-block" style="background:url(<?php echo  $mediaurl;?>) no-repeat center 20%;background-color:#aaa;background-size: cover; aspect-ratio:1/1;">
            <div class="overlay"></div>

            <div class="card-content" id="card-<?php echo $i;?>" style="overflow:hidden;align-items:end;display:flex;">
              <div class="content">
              <div class="card-top">
              <h3 class="title is-3 is-family-secondary has-text-white" id="title-<?php echo $i;?>">
                  <?php echo $heading;?>
              </h3>
            </div>
            <div class="is-hidden has-text-white" id="body-<?php echo $i;?>">
                <?php if($page->dataValue('type')):?>
                  <div class="has-text-weight-bold" style="border-bottom:solid 1px white;text-transform:uppercase;"><?php echo ucfirst($page->dataValue('type'));?></div>
                <?php endif;?>
                <?php if ($body): ?>
                  <?php
                    if(strlen($body) > 200):
                      $body = substr($body, 0, 200);
                      $body = substr($body, 0, strrpos($body, ' ')).' ...';
                    endif;
                  ?>
                    <?php echo $body; ?>
                <?php endif; ?>
                <!-- <?php if($page->dataValue('credits')):?>
                  <div class="has-text-centered">Door <?php echo $page->dataValue('credits'); ?></div>
                <?php endif;?>  -->
                </div> 
              </div>
            </div>
            </div>
          </div>
        </a>
      </div>
      <?php endforeach; ?>
    </div>
    <?php if($block->dataValue('link')):?>
      <div class="has-text-right">
        <a class="button is-outlined is-white" href="<?php echo $block->dataValue('link');?>">
          <?php if($block->dataValue('linktext')):?>
            <span><?php echo $block->dataValue('linktext');?></span>
          <?php else:?>
            <span>Lees meer</span>
          <?php endif;?>  
          <span class="icon is-small">
            <i class="fas fa-angle-right"></i>
          </span>
        </a>
      </div>  
    <?php endif;?>                
  </div>
</section>
<script>
function showCardContent(x){
  let id = '#card-' + x;
  let hover = '.card-hover-' + x;
  let idtitle = '#title-' + x;
  let idbody = '#body-' + x;
  $(hover).hover(function(){
    $( id ).css("height","100%");
    $( idtitle ).addClass("is-hidden");
    $( idbody ).removeClass( "is-hidden" );
  }, function() {
    $( idtitle ).removeClass( "is-hidden" );
    $( id ).css("height","50%");
    $( idbody ).addClass( "is-hidden" );
  })
}
</script>