<?php
$item = $marker->item();
$media = $marker->media();
?>
<?php if ($marker->label()): ?>
<!--<h3><?php echo $this->escapeHtml($marker->label()); ?></h3>-->
<?php endif; ?>
<?php if ($media): ?>
<img src="<?php echo $this->escapeHtml($media->thumbnailUrl('medium')); ?>">
<?php endif; ?>
<h4 class="title is-6">
    <?php echo $item->link($item->displayTitle(), null, ['target' => '_blank']); ?>
</h4>
<?php if ($media): ?>
<h4 class="title is-6">
    <?php echo $media->link($media->displayTitle(), null, ['target' => '_blank']); ?>
</h4>
<?php endif; ?>
