<?php
$translate = $this->plugin('translate');
?>
<style>
.card-content {
  background-color: rgba(0,0,0,0.36);
  padding: 1.5rem;
  bottom: 0;
  position:absolute;
  width: 100%;
  height: 40%;
  transition: transform 250ms;
  transition-property: height;
}
</style>
<section class="section page-browse-section">
  <div class="container">
  <?php if ($this->heading): ?>
      <div class="arrow-left"></div>
      <h2 class="title is-3 is-family-secondary"><?php echo $block->dataValue('heading');?></h2>
    <?php endif; ?>

    <div class="columns is-multiline">
      <?php
      $i=0;
      foreach ($pages as $page):
        $heading = $page->page()->title();
        $body = $page->dataValue('summary');
        $tagsArray = $page->dataValue('tags');
        $tags = implode(", ", $tagsArray);
        $i++;
      ?>
      <div class="column is-4">
        <?php
          $asset = $page->dataValue('cover');

          if (!$asset) {
              $mediaurl = "";
          }else{
            try {
                $media = $this->api()->read('assets', ['id' => $asset])->getContent();
                $mediaurl = $media->assetUrl('large');
            } catch (NotFoundException $e) {
                $mediaurl = "";
            }
          }

          $url = $page->page()->url();
        ?>
        <a href="<?php echo $url;?>">
          <div class="card equal-height card-hover-<?php echo $i;?>" onpointerenter="showCardContent(<?php echo $i;?>)";>              
            <div class="bg-block" style="background:url(<?php echo  $mediaurl;?>) no-repeat center 20%;background-color:#aaa;background-size: cover; min-height:250px;">
            <div class="overlay"></div>

            <div class="card-content" id="card-<?php echo $i;?>">
              <div class="content">
              <div class="card-top">
              <h3 class="title is-5 is-family-secondary has-text-white" id="title-<?php echo $i;?>">
                  <?php echo $heading;?>
              </h3>
            </div>
            <div class="is-hidden has-text-white" id="body-<?php echo $i;?>">
                <?php if ($body): ?>
                  <?php
                    if(strlen($body) > 200):
                      $body = substr($body, 0, 200);
                      $body = substr($body, 0, strrpos($body, ' ')).' ...';
                    endif;
                  ?>
                    <?php echo $body; ?>
                    <hr>
                <?php endif; ?>
                <?php if($page->dataValue('credits')):?>
                  <div>Door <?php echo $page->dataValue('credits'); ?></div>
                <?php endif;?> 
                <?php if($page->dataValue('type')):?>
                  <div><?php echo ucfirst($page->dataValue('type'));?></div>
                <?php endif;?>
                </div> 
              </div>
            </div>
            </div>
          </div>
        </a>
      </div>
      <?php endforeach; ?>
    </div>            
  </div>
</section>
<script>
function showCardContent(x){
  let id = '#card-' + x;
  let hover = '.card-hover-' + x;
  let idtitle = '#title-' + x;
  let idbody = '#body-' + x;
  $(hover).hover(function(){
    $( id ).css("height","100%");
    $( idtitle ).addClass("is-hidden");
    $( idbody ).removeClass( "is-hidden" );
  }, function() {
    $( idtitle ).removeClass( "is-hidden" );
    $( id ).css("height","40%");
    $( idbody ).addClass( "is-hidden" );
  })
}
</script>