<?php
/**
 * @var \Zend\View\Renderer\PhpRenderer $this
 * @var \Comment\Form\CommentForm $commentForm
 * @var \Omeka\Api\Representation\AbstractResourceEntityRepresentation $resource
 */

$plugins = $this->getHelperPluginManager();
$formElement = $plugins->get('formElement');
$formLabel = $plugins->get('formLabel');
$formText = $plugins->get('formText');
$formHidden = $plugins->get('formHidden');

$user = $this->identity();
$isAnonymous = empty($user);

$commentForm->prepare();
?>

<div style="max-width:700px;" id="comment-main-container" data-is-anonymous="<?= (int) $isAnonymous ?>">
    <?php // echo $this->form($commentForm) ?>
    <?php // TODO Add messages only if not set by layout. Anyway, they are available via json. ?>
    <?php if (false && $messages = $this->messages()): ?>
    <div id="comments-flash"><?= $messages ?></div>
    <?php endif; ?>

    <?= $this->form()->openTag($commentForm) ?>

<?php if ($isAnonymous): ?>
    <?php $element = $commentForm->get('o:name'); ?>
    <div class="field">
        <label class="label" for="o:name">Naam</label>
        <div class="control">
            <input class="input" type="text" name="o:name" placeholder="" value="">
        </div>
    </div>
    <?php $element = $commentForm->get('o:email'); ?>
    <div class="field">        
        <label class="label" for="o:email">Email</label>
        <div class="control">
            <input class="input" type="text" name="o:email" required="required" value="">
        </div>
    </div>
    
<?php endif; ?>

    <?php $element = $commentForm->get('o-module-comment:body'); ?>
    <div class="field">        
        <label class="label">Reactie</label>
        <div class="control">
            <textarea class="textarea is-primary" name="o-module-comment:body" placeholder="" required="required" rows="12"></textarea>
        </div>
    </div>

<?php if ($isAnonymous): ?>
    <?php if ($commentForm->has('g-recaptcha-response')): ?>
    <?php $element = $commentForm->get('g-recaptcha-response'); ?>
    <div class="field">
        <div class="inputs" required="required">
            <?= $formElement($element) ?>
        </div>
    </div>
    <?php endif; ?>
    <?php if ($commentForm->has('o-module-comment:check')): /* honeyspot */ ?>
    <?php $element = $commentForm->get('o-module-comment:check'); ?>
    <div class="field">
        <div class="inputs" required="required">
            <?= $formElement($element) ?>
        </div>
    </div>
    <?php endif; ?>
    <?php if ($commentForm->has('address')): /* quick anti-robot */ ?>
    <?php $element = $commentForm->get('address'); ?>
    <div class="field">
        <div class="field-meta">
            <?= $formLabel($element) ?>
        </div>
        <div class="inputs" required="required">
            <?= $formElement($element) ?>
        </div>
    </div>
    <?php $element = $commentForm->get('address_a'); ?>
    <?= $formHidden($element) ?>
    <?php $element = $commentForm->get('address_b'); ?>
    <?= $formHidden($element) ?>
    <?php endif; ?>
    <?php if ($commentForm->has('legal_agreement')): ?>
    <?php $element = $commentForm->get('legal_agreement'); ?>
    <div class="field">
        <div class="field-meta">
            <?= $formLabel($element) ?>
        </div>
        <div class="inputs" required="required">
            <?= $this->setting('comment_legal_text') ?>
            <?= $this->formCheckbox($element) ?>
        </div>
    </div>
    <?php endif; ?>
<?php endif; ?>

    <?= $formHidden($commentForm->get('resource_id')) ?>
    <?= $formHidden($commentForm->get('comment_parent_id')) ?>
    <?= $formHidden($commentForm->get('path')) ?>
    <?= $formHidden($commentForm->get('csrf_' . $resource->id())) ?>
    <?= $formHidden($commentForm->get('csrf')) ?>
    <?php $element = $commentForm->get('submit'); ?>
    <div class="field">
        <div class="field-meta">
        </div>
        <div class="inputs" required="required">
            <input type="submit" name="submit" class="button is-primary is-small" value="Verzend" aria-hidden="true">
        </div>
    </div>
    <?php //echo $this->formButton()->openTag($element) ?>
    <?php //echo $formLabel($element) ?>
    <?php //echo $this->formButton()->closeTag() ?>
    <?= $this->form()->closeTag() ?>
</div>
