<?php
$translate = $this->plugin('translate');
$prevText = $translate('<');
$nextText = $translate('>');
?>
<style>
.slider-next-page{
    position:fixed;
    display:flex;
    justify-content: center;
    align-items: center;
    left:auto;
    right:1em;
    top:50%;
}
.slider-prev-page{
    position:fixed;
    display:flex;
    justify-content: center;
    align-items: center;
    left:0.4em;
    right:auto;
    top:50%;
}
.fa-chevron-right::before,.fa-chevron-left {
    color:#edced3;
}
</style>
<?php if ($prevPage || $nextPage): ?>
<div class="site-page-pagination">
    <?php if($this->pageMetadata('type',$prevPage) == 'sub'):?>
        <div class="slider-prev-page">
            <a href="<?php echo $prevPage->siteUrl();?>"><i class="fa fa-chevron-left" style="font-size:3.5rem;"></i></a>
        </div>
    <?php endif;?>
    <?php if($nextPage && $this->pageMetadata('type') == 'sub' && $this->pageMetadata('type',$nextPage) == 'sub'):?>
        <div class="slider-next-page">
        <a href="<?php echo $nextPage->siteUrl();?>"><i class="fa fa-chevron-right" style="font-size:3.5rem;"></i></a>
    </div>
    <?php endif;?>
</div>
<?php endif; ?>