<?php
$escape = $this->plugin('escapeHtml');
$siteTitle = $site->title();
$this->htmlElement('html')->setAttribute('lang', $this->lang());
$this->htmlElement('html')->setAttribute('id', 'html');
$this->htmlElement('body')->setAttribute('class', 'has-navbar-fixed-top');
$this->headMeta()->setCharset('utf-8');
$this->headMeta()->appendName('viewport', 'width=device-width, initial-scale=1');
$this->headTitle($siteTitle)->setSeparator(' · ');
$this->headTitle()->append($this->setting('installation_title', 'Omeka S'));
$this->headLink()->prependStylesheet($this->assetUrl('css/style.min.css'));
//$this->headLink()->prependStylesheet($this->assetUrl('css/iconfonts.css', 'Omeka'));
//$this->headLink()->prependStylesheet('//fonts.googleapis.com/css?family=Open+Sans:400,400italic,600,600italic,700italic,700');
$this->headScript()->prependFile($this->assetUrl('js/default.js'));
$this->headScript()->prependFile($this->assetUrl('js/slick.js'));
$this->headScript()->prependFile($this->assetUrl('js/clamp.min.js'));
$this->headScript()->prependFile($this->assetUrl('js/global.js', 'Omeka'));
$this->headScript()->prependFile($this->assetUrl('vendor/jquery/jquery.min.js', 'Omeka'));
$this->trigger('view.layout');
$userBar = $this->userBar();
$primColor = '#edced3'; //#edced3

$url = $this->serverUrl(true);
if (strpos($url, 'page/home') !== false) {
    $home = false;
}else{
  $home = false;
}
?>
<?php echo $this->doctype(); ?>
<?php echo $this->htmlElement('html'); ?>
    <head>
        <?php echo $this->headMeta(); ?>
        <?php echo $this->headTitle(); ?>
        <?php echo $this->headLink(); ?>
        <?php echo $this->headStyle(); ?>
        <?php echo $this->headScript(); ?>
        <script src="https://kit.fontawesome.com/582fb8c29f.js" crossorigin="anonymous"></script>
       

        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bulma/0.7.4/css/bulma.min.css">
		<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bulma-carousel@4.0.3/dist/css/bulma-carousel.min.css">
    <link href="https://fonts.googleapis.com/css2?family=Montserrat:ital,wght@0,100;0,400;0,700;1,900&display=swap" rel="stylesheet">
    <link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Montserrat:ital,wght@0,100..900;1,100..900&display=swap" rel="stylesheet">
		<script async src="https://www.googletagmanager.com/gtag/js?id=UA-208068755-1"></script>
		<script>
		  window.dataLayer = window.dataLayer || [];
		  function gtag(){dataLayer.push(arguments);}
		  gtag('js', new Date());

		  gtag('config', 'UA-208068755-1');
		</script>
    <style>
      @media (max-width: 1024px) {
        .navigation {
          display: none;
        }
      };
      .has-icons-right > .has-addons {
        display:flex;
        padding: 3.5rem;
        background-color: azure;
      };
      .modal-content > #search-form {
        max-width: 100%;
      }
      .modal-content {
        margin: 4.5rem auto;
        width: 100%;
        max-height: calc(100vh - 40px);
        position: absolute;
      }
      .modal {
        justify-content: flex-start;
        z-index: 0;
      }
      .modal-background {
        background-color: rgba(00, 00, 00, 0.4) !important;
      }
      .zigzag {
        display: inline-block;
        position: relative;
      }

      .zigzag:after {
        content: '';
        height: 10px;
        width: 100%;
        position: absolute;
        background: url("https://cldup.com/MiGVGBh-0U.png");
        background-size: 18px;
        top: 35px;
        bottom: 0px;
        left: 0;
      }
      .arrow-left {
        width: 0; 
        height: 0; 
        border-top: 10px solid transparent;
        border-bottom: 10px solid transparent; 
        
        border-left:10px solid #edced3; 
        float: left;
        margin-top: 10px;
        margin-right: 5px;
      }
      #showNav {
        background-color: rgba(242,219,58,0.6);
      }
      .wrapper, .footer {
        font-family: Montserrat Light;
        color: #2d2d30;
      }
      .wrapper a {
        font-family: Montserrat SemiBold;
        color: #e29ca7;
      }
      .navbar .navigation li>a, .wrapper .button, .footer .button {
        font-family: Montserrat SemiBold;
        color: #2d2d30;
        border-bottom: solid 0.15em #f0a43d00;
        transition: text-decoration-color 900ms;
      }
      .navbar .navigation li>a {
        font-size: 1.1em;
      }
      .navbar .navigation li>a:hover {
        border-bottom-color: #e29ca7;
      }
      body .wrapper div>.title {
        font-family: Montserrat Bold !important;
        color:#2d2d30;
      }
      #logosite:hover{
        background-color: inherit !important;
      }
      .colour-button:hover {
        box-shadow: unset !important;
        transform:translateX(-5px);
        transition: all 1s ease;
    }
    .colour-button {
        transition: all 1s ease;
    }
    .value-piece::after {
      content:"" !important;
    }
    .card {
      border-radius: 4px;
    }
    .is-clickable{
      cursor: pointer !important;
    }


.bouncy-button {
  min-width: 15em;
	display: inline-block;
	font-family: "Montserrat", "Trebuchet MS", Helvetica, sans-serif;
	-webkit-font-smoothing: antialiased;
	position: relative;
	padding: 0.8em 1.4em;
	padding-left: 4.7em;
	background: #e29ca7;
	border: none;
	color: white;
	transition: 0.2s;
	&:before,
	&:after {
		position: absolute;
		top: 0;
		bottom: 0;
		left: 0;
		padding-top: inherit;
		padding-bottom: inherit;
		width: 2.8em;
		content: "\00a0";
		font-family: "FontAwesome", sans-serif;
		font-size: 1.2em;
		text-align: center;

		transition: 0.2s;
		transform-origin: 50% 60%;
	}
	&:before {
		background: #cb8c96;
	}
	&:hover {
		background: #d67584;
    cursor: pointer;
    &:before{
      background: #c26977;
    }
	}
	&:active,
	&:focus {
		background: darken(#e29ca7, 30%);
		outline: none;
	}
}

.arrow {
	background: #e29ca7;
	&:hover {
		background: darken(#e29ca7, 10%);
	}
	&:active,
	&:focus {
		background: darken(#e29ca7, 30%);
	}
	&:after {
		content: "\F054";
	}
	&:hover:after {
		-webkit-animation: bounceright 0.3s alternate ease infinite;
		animation: bounceright 0.3s alternate ease infinite;
	}
}

.share {
	background: #e29ca7;
	&:hover {
		background: darken(#e29ca7, 10%);
	}
	&:active,
	&:focus {
		background: darken(#e29ca7, 30%);
	}
	&:after {
		content: "\F1e0";
	}
	&:hover:after {
		-webkit-animation: bounceright 0.3s alternate ease infinite;
		animation: bounceright 0.3s alternate ease infinite;
	}
}

.download {
	background: #e29ca7;
	&:hover {
		background: darken(#e29ca7, 10%);
	}
	&:active,
	&:focus {
		background: darken(#e29ca7, 30%);
	}
	&:after {
		content: "\F019";
	}
	&:hover:after {
		-webkit-animation: bounceright 0.3s alternate ease infinite;
		animation: bounceright 0.3s alternate ease infinite;
	}
}

.disclaimer {
	background: #e29ca7;
	&:hover {
		background: darken(#e29ca7, 10%);
	}
	&:active,
	&:focus {
		background: darken(#e29ca7, 30%);
	}
	&:after {
		content: "\f15c";
	}
	&:hover:after {
		-webkit-animation: bounceright 0.3s alternate ease infinite;
		animation: bounceright 0.3s alternate ease infinite;
	}
}

.contact {
	background: #e29ca7;
	&:hover {
		background: darken(#e29ca7, 10%);
	}
	&:active,
	&:focus {
		background: darken(#e29ca7, 30%);
	}
	&:after {
		content: "\f0e0";
	}
	&:hover:after {
		-webkit-animation: bounceright 0.3s alternate ease infinite;
		animation: bounceright 0.3s alternate ease infinite;
	}
}

.viewall {
	background: #e29ca7;
	&:hover {
		background: darken(#e29ca7, 10%);
	}
	&:active,
	&:focus {
		background: darken(#e29ca7, 30%);
	}
	&:after {
		content: "\f06e";
	}
	&:hover:after {
		-webkit-animation: bounceright 0.3s alternate ease infinite;
		animation: bounceright 0.3s alternate ease infinite;
	}
}

.map {
	background: #e29ca7;
	&:hover {
		background: darken(#e29ca7, 10%);
	}
	&:active,
	&:focus {
		background: darken(#e29ca7, 30%);
	}
	&:after {
		content: "\f041";
	}
	&:hover:after {
		-webkit-animation: bounceright 0.3s alternate ease infinite;
		animation: bounceright 0.3s alternate ease infinite;
	}
}

.react {
	background: #e29ca7;
	&:hover {
		background: darken(#e29ca7, 10%);
	}
	&:active,
	&:focus {
		background: darken(#e29ca7, 30%);
	}
	&:after {
		content: "\f1d7";
	}
	&:hover:after {
		-webkit-animation: bounceright 0.3s alternate ease infinite;
		animation: bounceright 0.3s alternate ease infinite;
	}
}

@-webkit-keyframes bounceright {
	from {
		-webkit-transform: translateX(0);
	}
	to {
		-webkit-transform: translateX(3px);
	}
}

    </style>
    </head>

    <?php echo $this->htmlElement('body'); ?>
    <?php echo $userBar; ?>
    <?php if(!$home):?>
    <header>
        <nav class="navbar is-fixed-top" role="navigation" aria-label="main navigation" style="background-color:<?php echo $primColor;?>;">
          <div class="container">
          <div class="navbar-brand">
            <a class="navbar-item" href="<?php echo $site->url(); ?>/page/home" id="logosite">
              <?php if ($this->themeSetting('logo')): ?>
                  <img src="<?php echo $this->themeSettingAssetUrl('logo'); ?>" alt="<?php echo $escape($siteTitle); ?>" style="height: 3.5rem;"/>
              <?php else: ?>
                  <?php echo $escape($siteTitle); ?>
              <?php endif; ?>
            </a>
          </div>
          <div class="navbar-menu">
            <div class="navbar-start">

            </div> 
            <div class="navbar-end" style="text-transform:uppercase;">
                <?php
                  echo $site->publicNav()->menu()->renderMenu(null, [
                      'maxDepth' => $this->themeSetting('nav_depth', 0)
                  ]);
                ?>
              <div class="navbar-item">
                 <button class="button is-primary is-hidden" id="showNv" style="background-color: #f0a43d;">
                    <span class="icon is-small">
                      <i class="fas fa-bars"></i>
                    </span>
                  </button>
                 <button class="button is-primary" id="showSearch" style="background-color: #edced3;color:#2d2d30;">
                    <span class="icon is-small">
                      <i class="fas fa-search"></i>
                    </span>
                  </button>
                  <button class="button is-primary search-menu-close modal-close is-hidden" style="top:20px;background-color: #f0a43d"></button>
                </div>
             </div>
          </div>
        </div>
      </nav>
    </header>
    <?php endif;?>
    <div class="over-footer">
      <div class="wrapper">
        <?php echo $this->content;?>
      </div>
    </div>

    <footer class="footer" style="background-color:white;position:relative;z-index:-1;padding-top:1.5rem;bottom:0;">
        <div class="container">
          <nav class="level">
            <!-- Left side -->
            <div class="level-left">
              <div class="level-item">
                <a target="_blank" href="https://slimerfgoed.be/s/kadocerfgoed/page/disclaimer"><button class="disclaimer bouncy-button">Disclaimer</button></a>
              </div>
              <div class="level-item">
                <a target="_blank" href="https://slimerfgoed.be/s/kadocerfgoed/page/contact"><button class="contact bouncy-button">Contact</button></a>
              </div>
            </div>

            <!-- Right side -->
            <div class="level-right">
              <div class="level-item">
                <a target="_blank" href="https://kadoc.kuleuven.be"><img style="height:40px;padding:0 5px;" src="/themes/kadocerfgoed/asset/img/kadoc.PNG" /></a>
              </div>
              <div class="level-item">
                <a target="_blank" href="https://www.vlaanderen.be/"><img style="height:40px;padding:0 5px;" src="/themes/kadocerfgoed/asset/img/Logo_Vlaanderen.png" /></a>
              </div>
              <div class="level-item">
                <a target="_blank" href="https://libis.be"><img style="height:40px;padding:0 5px;" src="/themes/kadocerfgoed/asset/img/libissmall.png" /></a>
              </div>
            </div>
          </nav>
        </div>
      <?php if ($footerContent = $this->themeSetting('footer')): ?>
      <?php //echo $footerContent; ?>
      <?php endif; ?>
    </footer>

    <div class="search-menu modal">
      <div class="modal-background"></div>
        <div class="modal-content">
          <?php echo $this->partial('common/search-form'); ?>
        </div>
        
     </div>

     <div class="burger-menu modal">
       <div class="modal-background"></div>
         <div class="modal-content">
           <!-- Any other Bulma elements you want -->
           <?php echo $this->partial('common/search-form'); ?>
           <?php
             echo $site->publicNav()->menu()->renderMenu(null, [
                 'maxDepth' => $this->themeSetting('nav_depth') - 1
             ]);
           ?>
         </div>
         <button class="burger-menu-close modal-close is-large"></button>
      </div>
  </body>
  <script src="https://cdn.jsdelivr.net/npm/bulma-carousel@4.0.3/dist/js/bulma-carousel.min.js"></script>
  <script>
  $(document).ready(function() {
    bulmaCarousel.attach('#carousel-demo', {
			slidesToScroll: 1,
			slidesToShow: 1
		});
    $(".navigation li > a").addClass("has-text-weight-bold");
    // Check for click events on the navbar burger icon
    $("#showNav").click(function() {
        $(".burger-menu").toggleClass("is-active");
    });

    $("#showSearch").click(function() {
      $(".search-menu").addClass("is-active");
      $("#showSearch").addClass("is-hidden");
      $(".search-menu-close").removeClass("is-hidden");
    });

    $(".search-menu-close").click(function() {
       $(".search-menu").removeClass("is-active");
       $("#showSearch").removeClass("is-hidden");
       $(".search-menu-close").addClass("is-hidden");
    });
    $(".burger-menu-close").click(function() {
       $(".burger-menu").removeClass("is-active");
    });
    $(window).resize(function() {
      if ($(window).width() <= 1024) {
        $(".navigation").addClass("is-hidden");
        $("#showNav").removeClass("is-hidden");
      }
      if ($(window).width() > 1024) {
        $(".navigation").removeClass("is-hidden");
        $("#showNav").addClass("is-hidden");
      }
    });
  });
  </script>
</html>
