<?php
$translate = $this->plugin('translate');
$sitename = $block->page()->site()->title();
$color = "";
if($this->linkText == "Ontdek de kapelletjes van Vlaanderen"):
  $color = "color-section";
endif;  
$block->dataValue('limit');
$column = 12/$block->dataValue('limit');
?>
<section class="section browse-block <?php echo $color;?>">
  <div class="container">
    <div class="columns">
      <div class="column is-6">
          <?php if ($this->heading): ?>
            <h2 class="title is-3 is-family-secondary"><?php echo $this->heading; ?></h2>
            <?php if($block->dataValue('text')):?>
              <div class="content">
                <?php echo $block->dataValue('text');?>
              </div>
            <?php endif; ?>
          <?php endif; ?>
      </div>

      <?php if($this->linkText == "Ontdek de kapelletjes van Vlaanderen"):?>
        <div class="column">
            <?php if ($this->linkText && $this->link):?>
              <div class="has-text-right">
                  <a href="<?php echo $this->link;?>" class="button is-primary">
                    <span><?php echo $this->linkText;?></span>
                    <span class="icon is-small">
                      <i class="fas fa-angle-right"></i>
                    </span>
                  </a>
              </div>
            <?php endif;?>
        </div>
      <?php endif;?>
    </div>

    <?php if($this->resources):?>
    <div class="columns is-multiline <?php echo "is-".$columns;?>">
      <?php
      $headingTerm = $this->siteSetting('browse_heading_property_term', 'dcterms:title');
      $bodyTerm = $this->siteSetting('browse_body_property_term', 'dcterms:description');

      foreach ($this->resources as $resource):
          $heading = $resource->value($headingTerm, ['default' => $translate('[Untitled]')]);
          $body = $resource->displayDescription();
          if($resourceType == 'item-set'):
            $body = $resource->displayDescription();
          endif;
          $type = $resource->resourceTemplate();
          if($type):
            $type= $type->label();
          elseif($resourceType == 'item-set'):
            $type= 'Collectie';
          else:
            $type= "Object";
          endif;

          if($resourceType == 'item-set'):
            //$media = $resource->primaryMedia();
            $mediaurl = $resource->thumbnailDisplayUrl('square');
            
            if(!$mediaurl):
              $mediaurl= "";
            endif;
          else:
            $media = $resource->media();
            if($media):
              if(sizeof($this->resources) <= 2):
                $mediaurl = str_replace('http:', '', $media[0]->thumbnailUrl('large'));
              else:
                $mediaurl = str_replace('http:', '', $media[0]->thumbnailUrl('medium'));
              endif;
            else:
              $mediaurl = "";
            endif;
          endif;

          $url = $resource->url();
          $date = '';
        ?>

      <?php if($this->heading == "Partners"):?>
        <div class="column is-2 img-col">
          <div class="img-box">
            <a class="card-link-wrapper" href="<?php echo $url;?>">
              <div style="padding:0.5rem;background:#fff;">
                <img src="<?php echo  $mediaurl;?>">
              </div>
            </a>
          </div>
        </div>
        <div class="column is-6">      
          <div class="text-box">
            <h3 class="title is-5 is-family-secondary">
              <?php echo $resource->displayTitle();?>
            </h3>
            <div class="content">              
              <?php if ($body): ?>
                <p>
                  <?php $trunc = implode(" ", array_slice(explode(" ", $body), 0, 21)); ?>
                  <?php if(strlen($body) != strlen($trunc)):?>
                    <?php echo $trunc.' ...';?>
                  <?php else:?>
                    <?php echo $trunc;?>
                  <?php endif;?>
                </p>
              <?php endif; ?>
            </div>
            <div class="has-text-right">
              <a class="button is-outlined is-primary" href="<?php echo $url;?>">Meer info</a>
            </div>
          </div>  
        </div>
        <div class="column is-4"></div>
      <?php else:?>
        <div class="column <?php echo "is-".$columns;?>">
          <a class="card-link-wrapper" href="<?php echo $url;?>">
            <div class="card equal-height">
              <div class="card-bg card-bg-img-2"
                style="background:url(<?php echo  $mediaurl;?>) no-repeat center 20%;background-color:#ccc;background-size: cover;"
                >
              </div>
              <header class="card-header">
                <p class="card-header-title title is-4 is-family-secondary">
                    <span><?php echo $resource->displayTitle();?></span>
                </p>
              </header>
              <div class="card-content">
                <div class="content">
                  <?php if($resource->value('schema:datePublished') && $resourceType != 'item-set'):?>
                      <?php 
                        $date = $resource->value('schema:datePublished');
                        $date = date('d-m-Y',strtotime($date));
                      ?>
                      <p class="datering"><?php echo $date;?></p>
                  <?php endif;?>
                  <?php if ($body): ?>
                    <p>
                      <?php $trunc = implode(" ", array_slice(explode(" ", $body), 0, 21)); ?>
                      <?php if(strlen($body) != strlen($trunc)):?>
                        <?php echo $trunc.' ...';?>
                      <?php else:?>
                        <?php echo $trunc;?>
                      <?php endif;?>
                    </p>
                  <?php endif; ?>
                </div>
              </div>
              <div class="card-footer">
                <p class="card-footer-item">
                  <span>
                    <a href="<?php echo $resource->url();?>">
                    Alle gegevens
                    <span class="icon is-small">
                      <i class="fas fa-caret-right"></i>
                    </span>
                    </a>
                  </span>                  
                </p>
              </div>
            </div>
          </a>
        </div>        
      <?php endif;?>  
      
      <?php endforeach; ?>
    </div>       
    <?php if ($this->linkText && $this->link && $this->linkText != "Ontdek de kapelletjes van Vlaanderen"):?>
      <div class="has-text-right">
          <?php if($color):?>
            <a href="<?php echo $this->link;?>" class="button is-primary">
          <?php else:?>
            <a href="<?php echo $this->link;?>" class="button is-outlined is-primary">
          <?php endif;?>          
            <span><?php echo $this->linkText;?></span>
            <span class="icon is-small">
              <i class="fas fa-angle-right"></i>
            </span>
          </a>
      </div>
    <?php endif;?>

  <?php endif;?>
  </div>
</section>
