<?php
/*
 * Copyright BibLibre, 2016
 * Copyright, Daniel Berthereau, 2018-2020
 *
 * This software is governed by the CeCILL license under French law and abiding
 * by the rules of distribution of free software.  You can use, modify and/ or
 * redistribute the software under the terms of the CeCILL license as circulated
 * by CEA, CNRS and INRIA at the following URL "http://www.cecill.info".
 *
 * As a counterpart to the access to the source code and rights to copy, modify
 * and redistribute granted by the license, users are provided only with a
 * limited warranty and the software's author, the holder of the economic
 * rights, and the successive licensors have only limited liability.
 *
 * In this respect, the user's attention is drawn to the risks associated with
 * loading, using, modifying and/or developing or reproducing the software by
 * the user in light of its specific status of free software, that may mean that
 * it is complicated to manipulate, and that also therefore means that it is
 * reserved for developers and experienced professionals having in-depth
 * computer knowledge. Users are therefore encouraged to load and test the
 * software's suitability as regards their requirements in conditions enabling
 * the security of their systems and/or data to be ensured and, more generally,
 * to use and operate it in the same conditions as regards security.
 *
 * The fact that you are presently reading this means that you have had
 * knowledge of the CeCILL license and that you accept its terms.
 */

/**
 * @var \Zend\View\Renderer\PhpRenderer $this
 * @var \Search\Api\Representation\SearchPageRepresentation $searchPage
 * @var \Search\Query $query
 * @var \Search\Response $response
 */

$facets = $response->getFacetCounts();
?>

<?php if (!empty($facets)): ?>

<?php
$plugins = $this->getHelperPluginManager();
$translate = $plugins->get('translate');
$facetLabel = $plugins->get('facetLabel');
// facetCheckbox can be used instead (may require js).
$facetLink = $plugins->get('facetLink');
?>
<div class="column is-one-quarter">
  <aside class="facets">
      <h2 class="is-family-secondary"><?= $translate('Filters') ?></h2>
      <?php if($query->getQuery()):
        $filters = $query->getFilters();
        $params = "";
        if(isset($filters)):
          $params .= http_build_query($filters);
        endif;
        $sort = $query->getSort();
        if(isset($sort)):
          $params .= '&sort='.$sort;
        endif;
        if(isset($_GET['limit'])):
          $limit = http_build_query($_GET['limit']);
          $limit = str_replace("resource_template_id","[resource_template_id]",$limit);
          $params .= '&limit'.$limit;
        endif;
      ?>
      <div class="content">
          <a class="button is-info is-inverted is-outlined is-small" title="verwijder zoekopdracht" href="<?= parse_url($_SERVER["REQUEST_URI"], PHP_URL_PATH).'?q=&'.$params ?>">
            <span>Zoekopdracht: <?= htmlspecialchars(strip_tags($query->getQuery()));?></span><span class="icon is-small"><i class="fas fa-times"></i></span>
          </a>
      </div>
      <?php endif;?>
      <ul>
          <?php foreach ($facets as $name => $facetValues): ?>
            <?php
               $more = false;
               if(sizeof($facetValues)>10):
                  $more = array_slice($facetValues, 10);
                  $facetValues = array_slice($facetValues, 0, 10);
               endif;
            ?>
          <li class="search-facet">
              <h3 class="is-family-secondary"><?= $translate($facetLabel($name)) ?></h3>
              <ul class="search-facet-items">
                  <?php foreach ($facetValues as $facetValue): ?>
                  <li class="search-facet-item">
                      <?= $facetLink($name, $facetValue) ?>
                  </li>
                  <?php endforeach; ?>
                  <?php if($more):?>
                    <div class="more-link"><a class="has-text-grey" href=""><i class="fas fa-plus-square"></i><span>Show more</span></a></div>
                    <div class="more" style="display:none;">
                        <?php foreach ($more as $facetValue): ?>
                        <div class="form__item search-facet-item">
                            <?php echo $facetLink($name, $facetValue); ?>
                        </div>
                        <?php endforeach; ?>
                        <div class="less-link"><a class="has-text-grey" href=""><i class="fas fa-minus-square"></i><span>Show less</span></a></div>
                    </div>
                <?php endif;?>
              </ul>
          </li>
          <?php endforeach; ?>
      </ul>
  </aside>
</div>
<?php endif; ?>
<script>
    $(document).ready(function(){
        $( ".more-link a" ).click(function(e) {
            e.preventDefault();
            $(this).parent().hide();
            $(this).parent().next( "div" ).show();
        });
        $( ".less-link a" ).click(function(e) {
            e.preventDefault();
            $(this).parent().parent().hide();
            $(this).parent().parent().prev( ".more-link" ).show();
        });
    });
</script>
