<?php
use Laminas\Form\Element\Textarea;
?>

<h4>Text left</h4>
<?php
  $textarea = new Textarea("o:block[__blockIndex__][o:data][text1]");
  $textarea->setAttribute('class', 'block-html full wysiwyg');
  if ($block) {
      $textarea->setAttribute('value', $block->dataValue('text1'));
  }
?>
<?php echo $this->formRow($textarea);?>
<h4>Link left</h4>
<div class="field">
  <div class="inputs">
      <input type="text" class="" value="<?php echo (!isset($block) ? '' : $block->dataValue('link1')) ?>" name="o:block[__blockIndex__][o:data][link1]">
  </div>
</div>
<h4>Link text left</h4>
<div class="field">
  <div class="inputs">
      <input type="text" class="" value="<?php echo (!isset($block) ? '' : $block->dataValue('link_text1')); ?>" name="o:block[__blockIndex__][o:data][link_text1]">
  </div>
</div>
<hr>
<h4>Text right</h4>
<?php
  $textarea = new Textarea("o:block[__blockIndex__][o:data][text2]");
  $textarea->setAttribute('class', 'block-html full wysiwyg');
  if ($block) {
      $textarea->setAttribute('value', $block->dataValue('text2'));
  }
?>
<?php echo $this->formRow($textarea);?>
<h4>Link right</h4>
<div class="field">
 
  <div class="inputs">
      <input type="text" class="" value="<?php echo (!isset($block) ? '' : $block->dataValue('link2')) ?>" name="o:block[__blockIndex__][o:data][link2]">
  </div>
</div>
<h4>Link text right</h4>
<div class="field">
  <div class="inputs">
      <input type="text" class="" value="<?php echo (!isset($block) ? '' : $block->dataValue('link_text2')); ?>" name="o:block[__blockIndex__][o:data][link_text2]">
  </div>
</div>

