<?php
use Laminas\Http\Client;
$translate = $this->plugin('translate');
$escape = $this->plugin('escapeHtml');
$this->htmlElement('body')->appendAttribute('class', 'item resource show');
$embedMedia = $this->siteSetting('item_media_embed', false);
$itemMedia = $item->media();
$template = $item->resourceTemplate();
if($template):
  $type = $template->label();
else:
  $type = "";
endif;
?>
<section class="section breadcrumb-section">
  <div class="container">
    <nav class="breadcrumb" aria-label="breadcrumbs">
      <ul>
        <li><a href="/">Home</a></li>
        <?php if($type == 'Nieuwsbericht'):?>
        <li><a href="<?php echo "/s/toon/item/browse?resource_template_id=27";?>">Nieuws</a></li>
        <?php elseif($type == 'Actor (organisatie)'):?>
        <li><a href="<?php echo "/page/project";?>">Partner</a></li>
        <?php elseif($type == "Tool"):?>              
            <li><a href="/s/toon/objecten?facet[resource_template_id][]=<?php echo $type;?>">Draaiboek</a></li>  
        <?php else:?>              
            <li><a href="/s/toon/objecten?facet[resource_template_id][]=<?php echo $type;?>"><?php echo $type;?></a></li>  
        <?php endif;?>
        <li><?php echo $item->displayTitle(); ?></li>
      </ul>
    </nav>
  </div>
</section>
<section class="section">
  <div class="container">
    <h1 class="title is-2"><?php echo $item->displayTitle(); ?>
    <?php if($type == "Tool" && $types = $resource->value("dcterms:type", ["all" => true])):?>
          <div class="tags are-normal" style="margin-bottom:0;margin-top:0.5rem;">
          <? foreach($types as $dctype):?>
              <a href="<?php echo "/s/toon/draaiboek-zoeken?facet[type][]=".$dctype;?>" class="tag is-white is-medium"><?= $dctype ?></a></a>
          <?php endforeach;?>    
          </div>
    <?php endif;?>  
    <?php 
    if($item->value('schema:dateCreated')):?>
      <?php echo ", ".$item->value('schema:dateCreated').' - ';                 
      if($item->value('schema:dissolutionDate')):
        echo $item->value('schema:dissolutionDate');             
      endif;?>
    <?php endif;?>
    </h1>
    <?php if($item->value('schema:alternateName')): ?>
      <div class="subtitle is-3">
        <?php echo $item->value('schema:alternateName');?>
      </div>
    <?php endif;?>  
    <?php if($type == 'Nieuws'):?>
      <!--<h2 class="subtitle is-6"><?php echo date('d-m-Y',strtotime($item->value('dcterms:date'))); ?></h2>-->
    <?php endif;?>
  </div>
</section>

<section class="section">
<?php if($type == 'Nieuwsbericht'):?>  
    <div class="container" style="margin-bottom:1.5rem;">
      <div class="columns">
        <div class="column is-4">
          <?php
            $itemMedia = $resource->media();
            $sortedMedia = $this->SortMedia($itemMedia);
            $lightMedia = (isset($sortedMedia['lightMedia'])) ? $sortedMedia['lightMedia'] : null;
            $otherMedia = (isset($sortedMedia['otherMedia'])) ? $sortedMedia['otherMedia'] : null;
            ?>
            <?php if (isset($lightMedia)): ?>
                <?php echo $this->LightGalleryOutput($lightMedia); ?>
            <?php endif; ?>
           
        </div>
        <div class="column is-8">
            <div class="text-box content">
              <?php $date =  $item->value('schema:datePublished');?>
              <?php if($date):?>
                <?php $date = new DateTime($date->asHtml());?>
                <div style="margin-bottom:0.6rem;color:#666;">
                  <?php echo $date->format('d-m-Y');?>
                </div>            
              <?php endif;?> 
              <?php echo $item->value('schema:description');?>
              <?php $links = $item->value('schema:citation', array('all' => true));?>
              <?php if($links):?>
                <?php foreach($links as $link):?>
                  <div style="margin-top:0.6rem;">
                    <?php echo $link->asHtml();?>
                  </div>
                <?php endforeach;?>
              <?php endif;?>       
            </div>
        </div>
      </div>
    </div>
<?php elseif($type == "Tool"):?>
    <div class="container" style="margin-bottom:1.5rem;">
    <div class="zorg-lightbox">
      <?php
        $itemMedia = $resource->media();
        $sortedMedia = $this->SortMedia($itemMedia);
        $lightMedia = (isset($sortedMedia['lightMedia'])) ? $sortedMedia['lightMedia'] : null;
        $otherMedia = (isset($sortedMedia['otherMedia'])) ? $sortedMedia['otherMedia'] : null;
        ?>

        <?php if (isset($lightMedia)): ?>
            <?php echo $this->LightGalleryOutput($lightMedia); ?>
        <?php endif; ?>
        <!--<?php if (isset($otherMedia) && (count($otherMedia) > 0)): ?>
        
          <div id="other-media" class="property">
              <h4><?php echo $this->translate('Other Media'); ?></h4>
              <div class="values">
                  <?php foreach($otherMedia as $media): ?>
                  <div class="value">
                      <?php echo $media->linkPretty(); ?>
                  </div>
                  <?php endforeach; ?>
              </div>
          </div>
       
        <?php endif; ?>  -->
        </div>    
        <?php $refs =  $item->value('dcterms:references', array('all' => true)); ?>
        <?php $descs =  $item->value('dcterms:description', array('all' => true)); ?>
        <?php if($refs || $descs):?>
         <div class="text-box" >           
           <?php if($descs):?>
               <?php foreach($descs as $desc):?>
                 <div style="margin-bottom:0.3rem;">
                   <?php if ($res = $desc->valueResource()) {?>
                     <div class="icon-text">
                        <span class="icon">
                          <i class="fas fa-chevron-right"></i>
                        </span>
                        <span><?php echo $res->link($res->displayTitle());?></span>
                     </div>
                   <?php }elseif($desc->type() == 'uri'){ ?>
                     <div class="icon-text">
                        <span class="icon">
                          <i class="fas fa-chevron-right"></i>
                        </span>
                        <span><?php echo $desc->asHtml();?></span>
                     </div>
                   <?php }else{ ?>
                        <?php echo $desc;?>
                   <?php } ?>
                 </div>
              <?php endforeach;?>
           <?php endif;?>
           
           <?php if($refs):?>
             <hr />
             <?php foreach($refs as $ref):?>
               <?php $ref_e = explode("$$",$ref->__toString());?>
               <?php //var_dump($ref_e);?>
               <?php if($ref_e[0] != ", "):?>
                 <?php if(substr( $ref_e[0],0, 2 ) === ", "):?>
                  <?php $ref_e[0] = substr( $ref_e[0],2 );?>
                 <?php endif;?>
                 <div style="margin-bottom:0.3rem;">
                   <?php if($ref_e[1]):?>
                     <a target="_blank" href="<?php echo $ref_e[1]; ?>"><?php echo $ref_e[0]; ?></a>
                   <?php else:?>
                     <?php echo $ref_e[0]; ?>
                   <?php endif;?>
                 </div>
               <?php endif;?>
             <?php endforeach;?>
           <?php endif;?>        
      </div>
    <?php endif;?>                
   
    </div>   
<?php else:?>
    <div class="container" style="margin-bottom:1.5rem;">
      <div class="columns">
        <?php
          $itemMedia = $resource->media();
          $sortedMedia = $this->SortMedia($itemMedia);
          $lightMedia = (isset($sortedMedia['lightMedia'])) ? $sortedMedia['lightMedia'] : null;
          $otherMedia = (isset($sortedMedia['otherMedia'])) ? $sortedMedia['otherMedia'] : null;
        ?>

        <div class="column is-4"> 
          <?php if (isset($lightMedia)): ?>
              <?php echo $this->LightGalleryOutput($lightMedia); ?>
          <?php elseif(isset($otherMedia) && (count($otherMedia) > 0)): ?>       
            <div id="other-media" class="property">
                <h4><?php echo $this->translate('Other Media'); ?></h4>
                <div class="values">
                    <?php foreach($otherMedia as $media): ?>
                    <div class="value">
                        <?php echo $media->linkPretty(); ?>
                    </div>
                    <?php endforeach; ?>
                </div>
            </div>
          <?php endif; ?>        
        </div>  
       
        <div class="column">
          <div class="text-box" style="height:100%;margin-bottom:0;">              
            <?php if($item->value('schema:abstract')):?>
              <div class="description" style="margin-bottom:1rem;">
                <?php echo $item->value('schema:abstract');?>  
                <hr>
              </div>   
            <?php elseif($item->value('schema:description')):?>  
              <div class="description" style="margin-bottom:1rem;">
                <?php echo $item->value('schema:description');?>  
                <hr>
              </div>  
            <?php endif;?>  

           <?php echo $item->displayValues(); ?>
           <?php $itemSets = $item->itemSets(); ?>
           <?php if (count($itemSets) > 0): ?>
               
                 <h4 class="title is-6 is-family-secondary" style="margin:1.5rem 0 0.5rem 0">Collectie</h4>
               
               <ul>
                 <?php foreach ($itemSets as $itemSet): ?>
                 <li><a href="<?php echo $escape($itemSet->url()); ?>"><?php echo $itemSet->displayTitle(); ?></a></li>
                 <?php endforeach; ?>
               </ul>
           <?php endif; ?>           
          </div>
        </div>
     </div>
   </div>

   <?php $refs =  $item->value('dcterms:references', array('all' => true)); ?>
   <?php $descs =  $item->value('dcterms:description', array('all' => true)); ?>
   <?php if($refs || $descs):?>
   <div class="container">
      <div class="text-box" >        
        <?php if($descs):?>
          <?php foreach($descs as $desc):?>
            <div style="margin-bottom:0.3rem;">
              <?php if ($res = $desc->valueResource()) {?>
                <div class="icon-text">
                  <span class="icon">
                    <i class="fas fa-chevron-right"></i>
                  </span>
                  <span><?php echo $res->link($res->displayTitle());?></span>
                </div>
              <?php }elseif($desc->type() == 'uri'){ ?>
                <div class="icon-text">
                  <span class="icon">
                    <i class="fas fa-chevron-right"></i>
                  </span>
                  <span><?php echo $desc->asHtml();?></span>
                </div>
              <?php }else{ ?>
                  <?php echo $desc->asHtml();?>
              <?php } ?>
            </div>
          <?php endforeach;?>
        <?php endif;?>
           
        <?php if($refs):?>
          <hr />
          <?php foreach($refs as $ref):?>
            <?php $ref_e = explode("$$",$ref->__toString());?>
            <?php //var_dump($ref_e);?>
            <?php if($ref_e[0] != ", "):?>
              <?php if(substr( $ref_e[0],0, 2 ) === ", "):?>
              <?php $ref_e[0] = substr( $ref_e[0],2 );?>
              <?php endif;?>
              <div style="margin-bottom:0.3rem;">
                <?php if($ref_e[1]):?>
                  <a target="_blank" href="<?php echo $ref_e[1]; ?>"><?php echo $ref_e[0]; ?></a>
                <?php else:?>
                  <?php echo $ref_e[0]; ?>
                <?php endif;?>
              </div>
            <?php endif;?>
          <?php endforeach;?>
        <?php endif;?>
      </div>
    </div>
    <?php endif;?>  
<?php endif;?>
<?php 
    //PDF
    $itemMedia = $resource->media();
    $pdfs=[];
    $sortedMedia = $this->SortMedia($itemMedia);
    $lightMedia = (isset($sortedMedia['lightMedia'])) ? $sortedMedia['lightMedia'] : null;
    $otherMedia = (isset($sortedMedia['otherMedia'])) ? $sortedMedia['otherMedia'] : null;
       
    foreach($itemMedia as $media){
      if($media->mediaType() == "application/pdf"){
        $pdfs[] = $media;
      }
    };

    if($pdfs || $otherMedia){?>
      <div class="container">
        <div class="text-box">
          <h2>Documenten</h2>  
          <?php foreach($itemMedia as $media){?>  
            <?php if($media->mediaType() == "application/pdf"){?>
              <article class="media" style="max-width:800px;">
                <figure class="media-left">
                  <p class="image is-64x64">
                    <img src='<?php echo $media->thumbnailurl('square')?>'>
                  </p>
                </figure>
                <div class="media-content">
                  <div class="content">
                    <?php if($media->value("dcterms:title")):?>
                      <strong><?php echo $media->value("dcterms:title");?></strong><br>
                    <?php endif;?>  
                    <?php if($media->value("dcterms:description")):?>
                      <?php echo $media->value("dcterms:description");?>
                    <?php endif;?>  
                    <hr style="margin:0.5rem;">
                    <a class='button is-small is-primary' href='<?php echo $media->originalUrl();?>'><span class='icon-text'><span class='icon'><i class='fas fa-file-pdf'></i></span><span>Download PDF</span></span></a>
                  </div>                  
                </div>
              </article>
            <?php }?>
          <?php } ?>  

          <?php if (isset($otherMedia) && (count($otherMedia) > 0)): ?>
              <?php foreach($otherMedia as $media): ?>
                <article class="media" style="max-width:800px;">
                <figure class="media-left">
                  <p class="image is-64x64">
                    <img src='<?php echo $media->thumbnailurl('square')?>'>
                  </p>
                </figure>
                <div class="media-content">
                  <div class="content">
                    <?php if($media->value("dcterms:title")):?>
                      <strong><?php echo $media->value("dcterms:title");?></strong><br>
                    <?php endif;?>  
                    <?php if($media->value("dcterms:description")):?>
                      <?php echo $media->value("dcterms:description");?>
                    <?php endif;?>  
                    <hr style="margin:0.5rem;">
                    <a class='button is-small is-primary' href='<?php echo $media->originalUrl();?>'><span>Download</span></a>
                  </div>                  
                </div>
              </article>
              <?php endforeach; ?>
          <?php endif; ?>
        </div> 
      </div> 
    <?php }?>  
                        
    
    <?php
      $plugins = $this->getHelperPluginManager();
      $hasNext = $plugins->has('previousResource');
    ?>
    <?php if ($hasNext): ?>
      <div class="previous-next-items">
          <?php if ($previous = $this->previousResource($resource)): ?>
          <?= $previous->link($translate('Previous item'), null, ['class' => 'previous-item']) ?>
          <?php endif; ?>
          <?php if ($next = $this->nextResource($resource)): ?>
          <?= $next->link($translate('Next item'), null, ['class' => 'next-item']) ?>
          <?php endif; ?>
      </div>
    <?php endif; ?>      
      
     
  </div>   
</section>           
<?php
$page = $this->params()->fromQuery('page', 1);
$property = $this->params()->fromQuery('property');
$subjectValues = $item->subjectValues();
?>

<script>
  $(document).ready(function(){
    $('.slider-for').slick({
      slidesToShow: 1,
      slidesToScroll: 1,
      arrows: false,
      fade: true,
      centerMode: true
    });
    $('.slider-nav').slick({
      slidesToShow: 10,
      slidesToScroll: 1,
      asNavFor: '.slider-for',
      focusOnSelect: true
    });

    $('.slide-wrap').on('contextmenu', 'img', function(e){ 
      return false; 
    });

  });
</script>
