<?php
$this->headLink()->appendStylesheet($this->assetUrl('vendor/leaflet/leaflet.css', 'Mapping'));
$this->headScript()->appendFile($this->assetUrl('vendor/leaflet/leaflet.js', 'Mapping'));
$this->headLink()->appendStylesheet($this->assetUrl('vendor/leaflet.markercluster/MarkerCluster.css', 'Mapping'));
$this->headLink()->appendStylesheet($this->assetUrl('vendor/leaflet.markercluster/MarkerCluster.Default.css', 'Mapping'));
$this->headScript()->appendFile($this->assetUrl('vendor/leaflet.markercluster/leaflet.markercluster-src.js', 'Mapping'));
$this->headScript()->appendFile($this->assetUrl('vendor/leaflet.providers/leaflet-providers.js', 'Mapping'));
$this->headScript()->appendFile($this->assetUrl('js/control.fit-bounds.js', 'Mapping'));
$this->headScript()->appendFile($this->assetUrl('js/mapping-browse.js', 'Mapping'));
$this->headScript()->appendFile($this->assetUrl('js/advanced-search.js', 'Omeka'));
$query['mapping_basemap_provider'] = $query['mapping_basemap_provider'] ?? '';
?>

<style>
#mapping-map .kaart-button {
    position: absolute;
    left: 2rem;
    bottom: 2rem;
    z-index: 1000;
}
#mapping-map {
    position:sticky !important;
}
</style>

<div id="mapping-map" style="height:100vh;margin:50px auto;">
    <a class="kaart-button" href="#">
        <button class="bouncy-button arrow">Terug naar collectie</button>
    </a>
</div>

<?php foreach ($markers as $marker): ?>
<div class="mapping-marker-popup-content" style="display:none;"
    data-marker-id="<?php echo $this->escapeHtml($marker->id()); ?>"
    data-marker-lat="<?php echo $this->escapeHtml($marker->lat()); ?>"
    data-marker-lng="<?php echo $this->escapeHtml($marker->lng()); ?>"
>
    <?php 
        //$media = $marker->item()->primaryMedia();
        $mediaUrl = $marker->item()->thumbnailDisplayUrl('thumbnail');
        if(!$mediaUrl):
            $mediaUrl= "";
        endif;     
    ?>
    <?php if ($marker->label()): ?>
    <!--<h3><?php echo $this->escapeHtml($marker->label()); ?></h3>-->
    <?php endif; ?>
    <?php if ($mediaUrl):?>
        <img src="<?php echo $mediaUrl;?>">
    <?php endif;?>
    <h4 class="title is-6">
        <?php echo $marker->item()->link($marker->item()->displayTitle(), null, ['target' => '_blank']); ?>
    </h4>
    <?php if ($marker->media()): ?>
    <h4 class="title is-6">
        <?php echo $marker->media()->link($marker->media()->displayTitle(), null, ['target' => '_blank']); ?>
    </h4>
    <?php endif; ?>
</div>
<?php endforeach; ?>