<?php
$this->headLink()->appendStylesheet($this->assetUrl('vendor/leaflet/leaflet.css', 'Mapping'));
$this->headScript()->appendFile($this->assetUrl('vendor/leaflet/leaflet.js', 'Mapping'));
$this->headLink()->appendStylesheet($this->assetUrl('vendor/leaflet.markercluster/MarkerCluster.css', 'Mapping'));
$this->headLink()->appendStylesheet($this->assetUrl('vendor/leaflet.markercluster/MarkerCluster.Default.css', 'Mapping'));
$this->headScript()->appendFile($this->assetUrl('vendor/leaflet.markercluster/leaflet.markercluster-src.js', 'Mapping'));
$this->headScript()->appendFile($this->assetUrl('vendor/leaflet.providers/leaflet-providers.js', 'Mapping'));
$this->headScript()->appendFile($this->assetUrl('js/control.fit-bounds.js', 'Mapping'));
$this->headScript()->appendFile($this->assetUrl('js/mapping-browse.js', 'Mapping'));
$this->headScript()->appendFile($this->assetUrl('js/advanced-search.js', 'Omeka'));
$query['mapping_basemap_provider'] = $query['mapping_basemap_provider'] ?? '';
?>

<div id="mapping-map" style="height:100vh;margin:0 auto;">
    <a class="kaart-button button is-primary" href="/s/zorgerfgoed/objecten?facet[resource_template_id][]=Organisatie">
        <span>Bekijk een lijst van alle organisaties</span>
        <span class="icon is-small">
        <i class="fas fa-angle-right" aria-hidden="true"></i>
        </span>
    </a>
</div>

<!--
<form id="advanced-search">
    <?php echo $this->partial('common/advanced-search', ['query' => $query, 'resourceType' => 'item']); ?>
    <button><?php echo $this->translate('Search Map'); ?></button>
    <input type="hidden" name="mapping_basemap_provider" value="<?php echo $this->escapeHtml($query['mapping_basemap_provider']); ?>">
</form>
-->
<?php foreach ($markers as $marker): ?>
<div class="mapping-marker-popup-content" style="display:none;"
    data-marker-id="<?php echo $this->escapeHtml($marker->id()); ?>"
    data-marker-lat="<?php echo $this->escapeHtml($marker->lat()); ?>"
    data-marker-lng="<?php echo $this->escapeHtml($marker->lng()); ?>"
>
    <?php 
        $media = $marker->item()->primaryMedia();
    ?>
    <?php if ($marker->label()): ?>
    <!--<h3><?php echo $this->escapeHtml($marker->label()); ?></h3>-->
    <?php endif; ?>
    <?php if ($media):?>
        <?php if($media->getControllerName() == "media"):?>
            <img src="<?php echo $media->thumbnailUrl('medium');?>">
        <?php elseif($media->getControllerName() == "asset"):?>
            <img src="<?php echo $media->assetUrl();?>">
        <?php endif;?>    
    <?php endif;?>
    <h4 class="title is-6">
        <?php echo $marker->item()->link($marker->item()->displayTitle(), null, ['target' => '_blank']); ?>
    </h4>
    <?php if ($marker->media()): ?>
    <h4 class="title is-6">
        <?php echo $marker->media()->link($marker->media()->displayTitle(), null, ['target' => '_blank']); ?>
    </h4>
    <?php endif; ?>
</div>
<?php endforeach; ?>
