<?php
$escape = $this->plugin('escapeHtml');
$siteTitle = $site->title();
$this->htmlElement('html')->setAttribute('lang', $this->lang());
$this->headMeta()->setCharset('utf-8');
$this->headMeta()->appendName('viewport', 'width=device-width, initial-scale=1');
$this->headTitle($siteTitle)->setSeparator(' · ');
$this->headTitle()->append($this->setting('installation_title', 'Omeka S'));
$this->headLink()->prependStylesheet($this->assetUrl('css/style.min.css'));
$this->headLink()->prependStylesheet($this->assetUrl('css/selectize.css'));
//$this->headLink()->prependStylesheet($this->assetUrl('css/iconfonts.css', 'Omeka'));
//$this->headLink()->prependStylesheet('//fonts.googleapis.com/css?family=Open+Sans:400,400italic,600,600italic,700italic,700');
$this->headScript()->prependFile($this->assetUrl('js/default.js'));
$this->headScript()->prependFile($this->assetUrl('js/slick.js'));
$this->headScript()->prependFile($this->assetUrl('js/clamp.min.js'));
$this->headScript()->prependFile($this->assetUrl('js/selectize.js'));

$this->headScript()->prependFile($this->assetUrl('js/global.js', 'Omeka'));
$this->headScript()->prependFile($this->assetUrl('vendor/jquery/jquery.min.js', 'Omeka'));
$this->trigger('view.layout');
$userBar = $this->userBar();

$url = $this->serverUrl(true);
//echo 'url:'.$url;
if (strpos($url, 'page/home') !== false) {
    $home = true;
}else{
  $home = false;
}
?>
<?php echo $this->doctype(); ?>
<?php echo $this->htmlElement('html'); ?>
    <head>
        <?php echo $this->headMeta(); ?>
        <?php echo $this->headTitle(); ?>
        <?php echo $this->headLink(); ?>
        <?php echo $this->headStyle(); ?>
        <?php echo $this->headScript(); ?>
        <META HTTP-EQUIV="Access-Control-Allow-Origin" CONTENT="https://https://lib.is">
        <script src="https://kit.fontawesome.com/582fb8c29f.js" crossorigin="anonymous"></script>
        <link href="https://fonts.googleapis.com/css2?family=Manrope:wght@300;500;600;700;800&family=Raleway:ital,wght@0,300;0,400;0,500;0,600;1,300;1,400;1,500;1,600&display=swap" rel="stylesheet">
        <script src="https://unpkg.com/colcade@0/colcade.js"></script>
        <link rel="preconnect" href="https://fonts.googleapis.com">
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
        <link href="https://fonts.googleapis.com/css2?family=Barlow+Semi+Condensed:wght@400;600&family=Open+Sans:wght@300;400;500;600&display=swap" rel="stylesheet">     
        <!-- Google tag (gtag.js) --> 
        <script async src="https://www.googletagmanager.com/gtag/js?id=G-LP6SCS31MC"></script>
        <script> window.dataLayer = window.dataLayer || []; function gtag(){dataLayer.push(arguments);} gtag('js', new Date()); gtag('config', 'G-LP6SCS31MC'); </script>
    </head>

    <?php echo $this->htmlElement('body'); ?>
    <?php echo $userBar; ?>

    <header>
      <nav class="navbar" role="navigation" aria-label="main navigation">
        <div class="container">
          <div class="navbar-brand">
            <a class="navbar-item" href="<?php echo $site->url(); ?>">
            <?php if ($this->themeSetting('logo')): ?>
                  <img src="<?php echo str_replace("http:","https:",$this->themeSettingAssetUrl('logo')); ?>" alt="<?php echo $escape($siteTitle); ?>" />
              <?php endif; ?>
            </a>
            <a role="button" class="navbar-burger" aria-label="menu" aria-expanded="false">
                <span aria-hidden="true"></span>
                <span aria-hidden="true"></span>
                <span aria-hidden="true"></span>
            </a>
          </div>
          <div class="navbar-menu">
            <div class="navbar-start">
            <div class="navbar-item">
                <?php
                  echo $site->publicNav()->menu()->renderMenu(null, [
                      'maxDepth' => $this->themeSetting('nav_depth') - 1
                  ]);
                ?>
              </div>
            </div>
            <div class="navbar-end">
              
              <div class="navbar-item">
                  <button class="button is-primary showSearch">
                    <span class="icon is-small">
                      <i class="fas fa-search"></i>
                    </span>
                  </button>
              </div>
            </div>
          </div>
        </div>
      </nav>
     </div>
    </header>

    <section class="wrapper">    
      <div class="columns is-gapless">
        <div class="column is-narrow left-nav">
          <div class="logo">
            <a class="" href="<?php echo $site->url(); ?>">        
              <?php if ($this->themeSetting('logo')): ?>
                <img src="<?php echo $this->themeSettingAssetUrl('logo'); ?>" alt="<?php echo $escape($siteTitle); ?>" />
              <?php endif; ?>
            </a>
          </div>
          <?php
            echo $site->publicNav()->menu()->renderMenu(null, [
                'maxDepth' => $this->themeSetting('nav_depth') - 1
            ]);
          ?>
          <li class="search-button" style="text-align:left;">
              <a class="showSearch">
                <span>Zoeken</span><span class="icon is-small">
                  <i class="fas fa-search "></i>
                </span>
              </a>
          </li>
        </div>
        <div class="column">
          <div class="main-area"><?php echo $this->content; ?></div>    
        </div>
      </div>
        
      
    </section>

    <footer class="footer">
      <div class="container">
        <nav class="level">
            <!-- Left side -->
            <div class="level-left">
              <div class="level-item">
                <div class="logos">
                  <a href="https://kadoc.kuleuven.be/"><img alt="KU Leuven" src="<?php echo $this->assetUrl("img/kadoc.png");?>" /></a>
                  <a href="https://www.museumdrguislain.be/"><img alt="Museum Dr. Guislain Gent" src="<?php echo $this->assetUrl("img/MuseumDrGuislain_logo.jpg");?>" /></a>
                  <a href="https://www.vlaanderen.be/"><img alt="Vlaanderen,verbeelding werkt" src="<?php echo $this->assetUrl("img/vlaanderen.png");?>" /></a>
                </div>
              </div>
            </div>

            <!-- Right side -->
            <div class="level-right">
              <p class="level-item">
                </p><ul>
                  <li><a href="/page/disclaimer">Disclaimer</a></li>
                </ul><p></p>
            </div>
          </nav>
          <p style="font-size:0.9rem;">© KU Leuven, built by <a href="//libis.be">LIBIS</a></p>
      </div>
    </footer>

    <div class="search-menu modal">
      <div class="modal-background"></div>
        <div class="modal-content">
          <?php echo $this->partial('common/search-form'); ?>
        </div>
        <button class="search-menu-close modal-close is-large"></button>
     </div>

     <div class="burger-menu modal">
       <div class="modal-background"></div>
         <div class="modal-content">
           <!-- Any other Bulma elements you want -->
           <?php echo $this->partial('common/search-form'); ?>
           <?php
             echo $site->publicNav()->menu()->renderMenu(null, [
                 'maxDepth' => $this->themeSetting('nav_depth') - 1
             ]);
           ?>
         </div>
         <button class="burger-menu-close modal-close is-large"></button>
      </div>

      <div class="new-site-modal modal">
        <div class="modal-card">
          <div class="">
            <!-- Any other Bulma elements you want -->
            <div class="content">
              <div class="text-align:center"><img style="height:80px" src="<?php echo $this->assetUrl("img/Toon.png");?>"></div>
              <h3>DEZE WEBSITE WORDT VERNIEUWD!</h3>
              <p>Beste bezoeker,</p>  
              <p>Sedert januari 2024 gaat onze werking verder als landelijke dienstverlenende rol voor het erfgoed van en voor zorg en welzijn. En… daarbij hoort natuurlijk een nieuwe naam! Vanaf nu heten we TOON. Actief met Zorgarchief.  
              </p><p>Momenteel werken wij achter de schermen aan een nieuw vormgevingsmodel voor onze website dat helemaal past bij de vernieuwde werking.  
              </p><p>In tussentijd kan u op de huidige website nog steeds alle informatie terugvinden over de resultaten van het project ‘Zorgzaam (met) Erfgoed’ (het voortraject van TOON) en houden we u op de hoogte van de werking via de nieuwspagina.  
              </p><p>Bedankt voor uw begrip en geduld!  
              </p><p>Het TOON team</p>
            </div>
            
          </div>
          <button class="new-site-close modal-close is-large"></button>
          
        </div>
      </div>
  </body>
  <script>
  $(document).ready(function() {
    // Check for click events on the navbar burger icon
    $(".navbar-burger").click(function() {
        // Toggle the "is-active" class on both the "navbar-burger" and the "navbar-menu"
        //$(".navbar-burger").toggleClass("is-active");
        $(".burger-menu").toggleClass("is-active");
    });

    $(".showSearch").click(function() {
    $(".search-menu").addClass("is-active");
    });

    $(".search-menu-close").click(function() {
       $(".search-menu").removeClass("is-active");
    });
    $(".burger-menu-close").click(function() {
       $(".burger-menu").removeClass("is-active");
    });

    if(!localStorage.getItem("no_pop_up")){
      $(".new-site-modal").addClass("is-active");
    }

    $(".new-site-close").click(function() {
       $(".new-site-modal").removeClass("is-active");
       localStorage.setItem("no_pop_up",true);
    });

    $(".search-button").appendTo(".left-nav .navigation");
  });
  </script>

</html>
