<?php
use Laminas\Http\Client;
$translate = $this->plugin('translate');
$escape = $this->plugin('escapeHtml');
$this->htmlElement('body')->appendAttribute('class', 'item resource show');
$embedMedia = $this->siteSetting('item_media_embed', false);
$itemMedia = $item->media();
$template = $item->resourceTemplate();
if($template):
  $type = $template->label();
else:
  $type = "";
endif;
?>
<section class="section breadcrumb-section">
  <div class="container">
    <nav class="breadcrumb" aria-label="breadcrumbs">
      <ul>
        <li><a href="/">Home</a></li>
        <?php if($type == 'Kapel'):?>
          <li><a href="<?php echo "/s/kapellen/zoek-kapellen";?>">Kapelletjes</a></li>
        <?php elseif($type == 'Project'):?>
          <li><a href="<?php echo "/s/kapellen/inspiratiegids";?>">Inspiratiegids</a></li>
        <?php elseif($type == 'Actor (organisatie)'):?>              
          <li><a href="/s/kapellen/organisaties">Organisaties</a></li>  
        <?php endif;?>
        <li><?php echo $item->displayTitle(); ?></li>
      </ul>
    </nav>
  </div>
  <div class="container">
    <h1 class="title is-2 is-family-secondary"><?php echo $item->displayTitle(); ?>
    <?php 
    if($item->value('schema:dateCreated')):?>
      <?php echo ", ".$item->value('schema:dateCreated');?>     
    <?php endif;?>
    </h1>
    <?php if($item->value('schema:alternateName')): ?>
      <div class="subtitle is-4 is-family-secondary">
        <?php echo $item->value('schema:alternateName');?>
      </div>
    <?php endif;?>  
  </div>
</section>


<?php if($type == 'Nieuwsbericht' || $type == "Project" || $type == "Organisatie"):?>
  <section class="section">
    <div class="container">
      <div class="columns">
        <div class="column">
          <?php
            $itemMedia = $resource->media();
            $sortedMedia = $this->SortMedia($itemMedia);
            $lightMedia = (isset($sortedMedia['lightMedia'])) ? $sortedMedia['lightMedia'] : null;
            $otherMedia = (isset($sortedMedia['otherMedia'])) ? $sortedMedia['otherMedia'] : null;
            ?>
            <?php if (isset($lightMedia)): ?>
                <?php echo $this->LightGalleryOutput($lightMedia); ?>
            <?php endif; ?>
            <?php if (isset($otherMedia) && (count($otherMedia) > 0)): ?>
              <div class="column is-4"> 
                <div id="other-media" class="property">
                    <h4><?php echo $this->translate('Other Media'); ?></h4>
                    <div class="values">
                        <?php foreach($otherMedia as $media): ?>
                        <div class="value">
                            <?php echo $media->linkPretty(); ?>
                        </div>
                        <?php endforeach; ?>
                    </div>
                </div>
              </div>  
          <?php endif; ?>
        </div>
        <div class="column is-7">
           
           <?php $date =  $item->value('schema:datePublished');?>
           <?php if($date):?>
            <?php $date = new DateTime($date->asHtml());?>
            <div style="margin-bottom:0.6rem;color:#666;">
              <?php echo $date->format('d-m-Y');?>
            </div>            
            <?php endif;?> 
            <?php if($item->value('schema:abstract')):?>
                <?php $values = $item->value('schema:abstract',array('all'=>true)); ?>
                <div class="content">
                <?php foreach ($values as $value): ?>
                  <div class="content-value">
                    <?php echo $value->asHtml(); ?>
                  </div>      
                <?php endforeach; ?>
                </div>
            <?php endif;?>
            <?php if($item->value('dcterms:description')):?>
                <?php $values = $item->value('dcterms:description',array('all'=>true)); ?>
                <div class="content">
                <?php foreach ($values as $value): ?>
                  <div class="content-value">
                    <?php echo $value->asHtml(); ?>
                  </div>      
                <?php endforeach; ?>
                </div>
            <?php endif;?>
            <div class="content">         
              <?php if($item->value('project:samenvatting')):?>
              <?php echo $item->value('project:samenvatting')->asHtml();?>
              <?php endif;?>
              <?php if($item->value('project:faseEen')):?>
                <hr>  
                <h4 class="title is-5 is-family-secondary">Fase 1</h4>
                <?php echo $item->value('project:faseEen')->asHtml(); ?>
              <?php endif;?>  
              <?php if($item->value('project:faseTwee')):?>
                <hr>
                <h4 class="title is-5 is-family-secondary">Fase 2</h4>
                <?php echo $item->value('project:faseTwee')->asHtml(); ?>
              <?php endif;?>  
              <?php if($item->value('project:faseDrie')):?>
                <hr>
                <h4 class="title is-5 is-family-secondary">Fase 3</h4>
                <?php echo $item->value('project:faseDrie')->asHtml(); ?>
              <?php endif;?>
              <?php if($item->value('project:bewaardErfgoed')):?>
                <hr>
                <a class="button is-primary is-outlined" href="<?php echo $item->value('project:bewaardErfgoed');?>">Bewaard erfgoed</a>
              <?php endif;?>  
              <?php if($item->value('project:gerelateerdErfgoed')):?>
                <h4 class="title is-4 is-family-secondary">Bewaard erfgoed</h4>
                <div class="content values erfgoed">
                  <?php $values = $item->value('project:gerelateerdErfgoed',array('all'=>true)); ?>
                  <?php foreach ($values as $value): ?>
                          <?php echo $value->asHtml(); ?>
                  <?php endforeach; ?>
                </div>
              <?php endif;?>
            </div>
            <?php $links = $item->value('activiteit:meerInfo', array('all' => true));?>
            <?php if($links):?>              
              <?php foreach($links as $link):?>                
                <?php echo $link->asHtml();?>
              <?php endforeach;?>
            <?php endif;?> 
            <?php $links = $item->value('project:projectUrl', array('all' => true));?>
            <?php if($links):?>              
              <?php foreach($links as $link):?>                
                <?php echo $link->asHtml();?>
              <?php endforeach;?>
            <?php endif;?>       
           </div>
          
         </div>
        </div>
      </div>
    </div>
  </section>
<?php else:?>
  <section class="section item-section">
    <div class="container" style="margin-bottom:1.5rem;">      
      <?php
        $itemMedia = $resource->media();
        $itemMedia = array_reverse($itemMedia);
        $sortedMedia = $this->SortMedia($itemMedia);
        $lightMedia = (isset($sortedMedia['lightMedia'])) ? $sortedMedia['lightMedia'] : null;
        $otherMedia = (isset($sortedMedia['otherMedia'])) ? $sortedMedia['otherMedia'] : null;
      ?>
      <?php if (isset($lightMedia)): ?>
          <?php echo $this->LightGalleryOutput($lightMedia); ?>
      <?php endif; ?>
      <!--<?php if (isset($otherMedia) && (count($otherMedia) > 0)): ?>
      
          <div id="other-media" class="property">
              <h4><?php echo $this->translate('Other Media'); ?></h4>
              <div class="values">
                  <?php foreach($otherMedia as $media): ?>
                  <div class="value">
                      <?php echo $media->linkPretty(); ?>
                  </div>
                  <?php endforeach; ?>
              </div>
          </div>
      <?php endif; ?>-->    

      <div class="columns">
        <div class="column is-8">

          <div class="tabs is-centered">
            <ul>
              <li class="tab"><a href="#Identificatie">Identificatie</a></li>
              <li class="tab"><a href="#Ontstaan-en-tradities">Ontstaan en tradities</a></li>
              <li class="tab"><a href="#Exterieur">Exterieur</a></li>
              <li class="tab"><a href="#Interieur">Interieur</a></li>
              <li class="tab"><a href="#Beheer-en-toestand">Beheer en toestand</a></li>
              <li class="tab"><a href="#Bronnen-en-links">Bronnen en links</a></li>
            </ul>
          </div>
          <div id="Identificatie" class="tab-pane animated">  
            <?php echo $item->displayValues(); ?>              
          </div>

          <?php //$this->trigger('view.show.after'); ?>
          <?php
            $plugins = $this->getHelperPluginManager();
            $hasNext = $plugins->has('previousResource');
          ?>
          <?php if ($hasNext): ?>
            <div class="previous-next-items">
                <?php if ($previous = $this->previousResource($resource)): ?>
                <?= $previous->link($translate('Previous item'), null, ['class' => 'previous-item']) ?>
                <?php endif; ?>
                <?php if ($next = $this->nextResource($resource)): ?>
                <?= $next->link($translate('Next item'), null, ['class' => 'next-item']) ?>
                <?php endif; ?>
            </div>
          <?php endif; ?>

          <?php
          $page = $this->params()->fromQuery('page', 1);
          $property = $this->params()->fromQuery('property');
          $subjectValues = $item->displaySubjectValues($page, 25, $property);
          ?>
          
          <?php if ($subjectValues): ?>
          <div id="item-linked" style="margin-top:2rem;">
              <h3 class="title is-4 is-family-secondary"><?php echo $translate('Lees meer over deze kapel'); ?></h3>
              <?php echo $subjectValues; ?>
          </div>
          <?php endif; ?>
        </div>
        <div class="column">
          <div class="content description">
            <?php echo $this->partial('mapping/index/show', ['item' => $resource]);?>
           <br><p>Heb je meer informatie over deze kapel, of zijn niet alle gegevens correct?</p>
            <a class="button is-primary" href="<?php echo $item->url().'/edit';?>">Pas deze kapel aan</a>
          </div>
        </div>
      </div>
    </div>
  </section>  
<?php endif;?>

<?php
$page = $this->params()->fromQuery('page', 1);
$property = $this->params()->fromQuery('property');
$subjectValues = $item->subjectValues();
?>

<script>
  $(document).ready(function(){
    $('.slider-for').slick({
      slidesToShow: 1,
      slidesToScroll: 1,
      arrows: false,
      fade: true,
      centerMode: true
    });
    $('.slider-nav').slick({
      slidesToShow: 10,
      slidesToScroll: 1,
      asNavFor: '.slider-for',
      focusOnSelect: true
    });

    $('.slide-wrap').on('contextmenu', 'img', function(e){ 
      return false; 
    });

    $('li.tab:first').addClass('is-active');
    $('.tab-pane:first').addClass('is-active');

    $( "li.tab" ).each(function( index ) {
      var hash = $(this).children('a').eq(0).attr('href');
      if($(hash).length){

      }else{
        $( this ).hide();
      }
    });

    $('li.tab').click(function(e) {
      e.preventDefault();
      var hash = $(this).children('a').eq(0).attr('href');
      $('.tab-pane').removeClass('is-active');
      $(hash).addClass('is-active');
      $('li.tab').removeClass('is-active');
      $(this).addClass('is-active');
      return true;
    });

  });
</script>
