<h4>Url of contact page</h4>
<div class="field">
  <div class="inputs">
      <input type="text" class="" value="<?php echo (!isset($block) ? '' : $block->dataValue('contactUrl')); ?>" name="o:block[__blockIndex__][o:data][contactUrl]">
  </div>
</div>

<h4>Button text</h4>
<div class="field">
  <div class="inputs">
      <input type="text" class="" value="<?php echo (!isset($block) ? '' : $block->dataValue('text')); ?>" name="o:block[__blockIndex__][o:data][text]">
  </div>
</div>
