<?php
$this->headLink()->appendStylesheet($this->assetUrl('vendor/leaflet/leaflet.css', 'Mapping'));
$this->headScript()->appendFile($this->assetUrl('vendor/leaflet/leaflet.js', 'Mapping'));
$this->headLink()->appendStylesheet($this->assetUrl('vendor/leaflet.markercluster/MarkerCluster.css', 'Mapping'));
$this->headLink()->appendStylesheet($this->assetUrl('vendor/leaflet.markercluster/MarkerCluster.Default.css', 'Mapping'));
$this->headScript()->appendFile($this->assetUrl('vendor/leaflet.markercluster/leaflet.markercluster-src.js', 'Mapping'));
$this->headScript()->appendFile($this->assetUrl('vendor/leaflet.providers/leaflet-providers.js', 'Mapping'));
$this->headScript()->appendFile($this->assetUrl('js/control.fit-bounds.js', 'Mapping'));
$this->headScript()->appendFile($this->assetUrl('js/mapping-browse.js', 'Mapping'));
$this->headScript()->appendFile($this->assetUrl('js/advanced-search.js', 'Omeka'));
$query['mapping_basemap_provider'] = $query['mapping_basemap_provider'] ?? '';
?>

<section class="map-browse-section">
    <div class="columns">
        <div class="column is-3">
            
            <div class="mapping-search-box">
                <!--  <form id="advanced-search" method="get" action="<?php //echo $this->escapeHtml($this->url(null, ['action' => 'browse'], true)); ?>">
                    <?php //echo $this->partial('common/advanced-search',['query' => $this->params()->fromQuery(), 'resourceType' => 'item']); ?>
                    <div id="page-actions">
                        <input type="submit" name="submit" value="Zoeken">
                    </div>
                </form>
                -->         
                
                <form class="has-icons-right" action="<?php echo $this->escapeHtml($this->url(null, ['action' => 'browse'], true)); ?>" id="search-form">
                <?php $searchValue = $this->escapeHtml($this->params()->fromQuery('fulltext_search', ''));?>
              
                    <div class="field has-addons">
                        <div class="control">
                            <input class="input" type="search" name="fulltext_search" value="<?php echo $searchValue; ?>"
                            placeholder="Zoek op de kaart"
                            aria-label="Zoeken">
                        </div>
                        <div class="control">
                            <a class="button is-primary">
                            <span class="icon is-large">
                                <i class="fas fa-search"></i>
                            </span>
                            </a>
                        </div>
                    </div>   
                </form>
                <?php
                    //echo $this->references()->displayListForTerm('dcterms:title');
                    /*
                    property[0][joiner]=or&property[0][property]=dcterms:title&property[0][type]=eq&property[0][text]=Lorem ipsum
                    */

                    $gemeente = ($this->references()->list('locatie:gemeente',$this->params()->fromQuery(),array()));        
                    
                    if($gemeente["o:references"]):        
                        echo "<h4 class='title is-5'>Gemeente</h4>";
                        echo "<ul class='reference-list'>";
                        foreach($gemeente["o:references"] as $gemeente):
                            $gemeente_query = "property[0][joiner]=or&property[0][property]=4738&property[0][type]=eq&property[0][text]=".$gemeente["val"];
                            echo "<li><a href='".$this->escapeHtml($this->url(null, ['action' => 'browse'], true))."?".$gemeente_query."'>".$gemeente["val"]." (".$gemeente["total"].")</a></li>";
                        endforeach; 
                        echo "</ul>";   
                    endif;

                    $loc = $this->params()->fromQuery();
                    if(isset($loc["property"][0]["property"])):
                        $loc = $loc["property"][0]["property"];        
                    else:
                        $loc = "";               
                    endif;

                    if($loc == "4738" || $loc == "4732"):
                        $deelgemeente = ($this->references()->list('locatie:deelgemeente',$this->params()->fromQuery(),array())); 
                        if($deelgemeente["o:references"]): 
                            echo "<h4 class='title is-5'>Deelgemeente</h4>";
                            echo "<ul class='reference-list'>";
                            foreach($deelgemeente["o:references"] as $deelgemeente):
                                $deelgemeente_query = "property[0][joiner]=or&property[0][property]=4732&property[0][type]=eq&property[0][text]=".$deelgemeente["val"];
                                echo "<li><a href='".$this->escapeHtml($this->url(null, ['action' => 'browse'], true))."?".$deelgemeente_query."'>".$deelgemeente["val"]." (".$deelgemeente["total"].")</a></li>";
                            endforeach; 
                            echo "</ul>";  
                        endif;
                        echo "<br><a href='https://kapelletjes.be/map-browse'>Toon alle kapellen</a>";
                    endif;
                ?>                  
                    
                <hr>
                <a class="kaart-button" href="/s/kapellen/zoek-kapellen?resource_template_id=Kapel">
                    <span class="icon-text">
                        <span>Bekijk een lijst van alle kapellen</span>
                        <span class="icon is-small">
                        <i class="fas fa-angle-right" aria-hidden="true"></i>
                        </span>
                    </span>
                </a>
                <a class="kaart-button" href="/page/contact">
                    <span class="icon-text">
                        <span>Voeg een kapel toe</span>
                        <span class="icon is-small">
                        <i class="fas fa-plus" aria-hidden="true"></i>
                        </span>
                    </span>
                </a>
                    
                </div>
        </div>
        <div class="column">
            <div id="mapping-map" style="height:100vh;margin:0 auto;">
                
                </div></div>
    </div>
</section>

<?php foreach ($markers as $marker): ?>
<div class="mapping-marker-popup-content" style="display:none;"
    data-marker-id="<?php echo $this->escapeHtml($marker->id()); ?>"
    data-marker-lat="<?php echo $this->escapeHtml($marker->lat()); ?>"
    data-marker-lng="<?php echo $this->escapeHtml($marker->lng()); ?>"
>
    <?php 
        //$media = $marker->item()->primaryMedia();
       /* $mediaUrl = $marker->item()->thumbnailDisplayUrl('medium');
        if(!$mediaUrl):
            $mediaUrl= "";
        endif;*/     
        $mediaUrl= "";
    ?>
    <?php if ($marker->label()): ?>
    <!--<h3><?php echo $this->escapeHtml($marker->label()); ?></h3>-->
    <?php endif; ?>
    <?php if ($mediaUrl):?>
        <img src="<?php echo $mediaUrl;?>">
    <?php endif;?>
    <h4 class="title is-6">
        <?php echo $marker->item()->link($marker->item()->displayTitle(), null, ['target' => '_blank']); ?>
    </h4>
    <?php //if ($marker->media()): 
    
       //echo $marker->media()->link($marker->media()->displayTitle(), null, ['target' => '_blank']);
   
     //endif; ?>
</div>
<?php endforeach; ?>
